// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace McpServer.SpecFlow.Tests.Features.Tunnel
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TunnelProvidersFeature : object, global::Xunit.IClassFixture<TunnelProvidersFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Tunnel", "Tunnel Providers", "  As a server operator\n  I want the server to expose itself to the internet via p" +
                "luggable tunnel providers\n  So that remote AI agents can connect to a locally ru" +
                "nning server", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TunnelProviders.feature"
#line hidden
        
        public TunnelProvidersFeature(TunnelProvidersFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Tunnel/TunnelProviders.feature", "Feature: Tunnel Providers\n  As a server operator\n  I want the server to expose it" +
                    "self to the internet via pluggable tunnel providers\n  So that remote AI agents c" +
                    "an connect to a locally running server\n\n  # FR-MCP-015 / TR-MCP-TUN-001 / TR-MCP" +
                    "-TUN-002 / TR-MCP-TUN-003 / TEST-MCP-011\n\n  Scenario: Ngrok tunnel provider uses" +
                    " NGROK_AUTHTOKEN environment variable\n    # TR-MCP-TUN-003 — auth token passed v" +
                    "ia env var, not CLI argument\n    Given the NgrokTunnelProvider is configured wit" +
                    "h auth token \"test-token\"\n    When the NgrokTunnelProvider builds its process st" +
                    "art info\n    Then the process arguments should not contain the auth token\n    An" +
                    "d the environment variable \"NGROK_AUTHTOKEN\" should be set to \"test-token\"\n\n  Sc" +
                    "enario: Tunnel process stop is TOCTOU-safe via try-catch on Process.Kill\n    # T" +
                    "R-MCP-TUN-002 — Process.Kill wrapped in try-catch for InvalidOperationException\n" +
                    "    Given a tunnel process has already exited before StopAsync is called\n    Whe" +
                    "n StopAsync is called on the tunnel provider\n    Then no InvalidOperationExcepti" +
                    "on is thrown\n\n  Scenario: Tunnel process stop waits up to 5 seconds for graceful" +
                    " exit\n    # TR-MCP-TUN-002 — WaitForExit(5000) timeout\n    Given a tunnel provid" +
                    "er has an active process\n    When StopAsync is called\n    Then the provider wait" +
                    "s at most 5000 milliseconds for the process to exit\n\n  Scenario: FRP tunnel conf" +
                    "ig file is deleted after stop\n    # TR-MCP-TUN-002 — FRP config files cleaned up" +
                    "\n    Given the FrpTunnelProvider wrote a config file\n    When StopAsync is calle" +
                    "d on the FrpTunnelProvider\n    Then the FRP config file should be deleted\n\n  Sce" +
                    "nario: Tunnel provider is registered as IHostedService when provider name is set" +
                    "\n    # TR-MCP-TUN-001 — registered as IHostedService conditionally\n    Given tun" +
                    "nel provider \"ngrok\" is configured\n    Then the DI container should contain a re" +
                    "gistered IHostedService for the tunnel provider\n\n  Scenario: Cloudflare tunnel u" +
                    "ses cloudflared quick tunnel when no named tunnel configured\n    Given the Cloud" +
                    "flareTunnelProvider is configured without a tunnel name\n    When the CloudflareT" +
                    "unnelProvider builds its process start info\n    Then the process arguments shoul" +
                    "d contain \"tunnel\"\n    And the process arguments should contain \"run\"\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Tunnel/TunnelProviders.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Tunnel Providers", "  As a server operator\n  I want the server to expose itself to the internet via p" +
                        "luggable tunnel providers\n  So that remote AI agents can connect to a locally ru" +
                        "nning server", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Ngrok tunnel provider uses NGROK_AUTHTOKEN environment variable", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the NgrokTunnelProvider is configured with auth token \"test-token\"", null, null, "65b2718de6fc005eb770d365fdb8ef9f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the NgrokTunnelProvider builds its process start info", null, null, "dedfa289bdb7ac59beca8ca14184acd6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the process arguments should not contain the auth token", null, null, "efcb85b68c5fff5395dee6d3d848648a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the environment variable \"NGROK_AUTHTOKEN\" should be set to \"test-token\"", null, null, "e167eb2c25f09e58b15dc1f52c9d60dc")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "686437841443fe5fb158ce3ceaf51721")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Tunnel process stop is TOCTOU-safe via try-catch on Process.Kill", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a tunnel process has already exited before StopAsync is called", null, null, "d7e448f8ba952b588b797515dec5c26d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "StopAsync is called on the tunnel provider", null, null, "ed80f306ea1f875dbd4235df9bba83e8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "no InvalidOperationException is thrown", null, null, "5cc5364bba7673558dcc3b8985c2999d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "c6dfc62814447b56897d3bc3eaf5c15a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Tunnel process stop waits up to 5 seconds for graceful exit", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a tunnel provider has an active process", null, null, "02e95acd81323b55a50b711dad394db8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "StopAsync is called", null, null, "e6061e453885aa58bdff235e3d264202"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the provider waits at most 5000 milliseconds for the process to exit", null, null, "348b9b32c2b283548d4f88c92db2f19d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "589770528d691656802177c0fcce9c91")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "FRP tunnel config file is deleted after stop", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the FrpTunnelProvider wrote a config file", null, null, "215f5128360d165398302238972d82c9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "StopAsync is called on the FrpTunnelProvider", null, null, "93a60a1288ea145b81274ac691a644fb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the FRP config file should be deleted", null, null, "c4278df4d40e2555879db7d3df2354fb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0fbac187c8a0d258983864355fd33a7d")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Tunnel provider is registered as IHostedService when provider name is set", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "tunnel provider \"ngrok\" is configured", null, null, "4b82a9bedeb13c5980e68b94f1aec139"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the DI container should contain a registered IHostedService for the tunnel provid" +
                                                            "er", null, null, "1e886540f6841d5a87ec3ce6d5e63f07")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "aa3f225afbe3a25c88e0a69051ed8683")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Cloudflare tunnel uses cloudflared quick tunnel when no named tunnel configured", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the CloudflareTunnelProvider is configured without a tunnel name", null, null, "e98812e6829fb3559ccbdcf516f58a34"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the CloudflareTunnelProvider builds its process start info", null, null, "5888fed7dd1c2453b1e3473e0c4339c0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the process arguments should contain \"tunnel\"", null, null, "5951a4631e88135e9184241652de1013"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the process arguments should contain \"run\"", null, null, "9e08065be2e2ca53bd83671902189537")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "868ee42c2ddca252ac50c5ce6ff63f50"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(1)), "  # FR-MCP-015 / TR-MCP-TUN-001 / TR-MCP-TUN-002 / TR-MCP-TUN-003 / TEST-MCP-011"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(1)), "    # TR-MCP-TUN-003 — auth token passed via env var, not CLI argument"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(1)), "    # TR-MCP-TUN-002 — Process.Kill wrapped in try-catch for InvalidOperationExce" +
                                    "ption"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(1)), "    # TR-MCP-TUN-002 — WaitForExit(5000) timeout"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(1)), "    # TR-MCP-TUN-002 — FRP config files cleaned up"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(1)), "    # TR-MCP-TUN-001 — registered as IHostedService conditionally")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("083b157a311ef454a032c65494878f02", "Features/Tunnel/TunnelProviders.feature", "Ngrok tunnel provider uses NGROK_AUTHTOKEN environment variable", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "65b2718de6fc005eb770d365fdb8ef9f"}), "620f7a3954620d53b98cb1fa19400f80", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the NgrokTunnelProvider is configured with auth token \"test-token\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "dedfa289bdb7ac59beca8ca14184acd6"}), "cedc21c6cb98ad5a8a00bcb680d172c7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the NgrokTunnelProvider builds its process start info"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "efcb85b68c5fff5395dee6d3d848648a"}), "29faf76a11b81d5680399894d9f0cfdc", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the process arguments should not contain the auth token"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e167eb2c25f09e58b15dc1f52c9d60dc"}), "c1a79a7baecadb589fb9b25d532cd4da", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the environment variable \"NGROK_AUTHTOKEN\" should be set to \"test-token\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "686437841443fe5fb158ce3ceaf51721"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b095706e192a5e579d5c488c963b727e", "Features/Tunnel/TunnelProviders.feature", "Tunnel process stop is TOCTOU-safe via try-catch on Process.Kill", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d7e448f8ba952b588b797515dec5c26d"}), "fb1a157f0a892f528bc150d5d39ab1f0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a tunnel process has already exited before StopAsync is called"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ed80f306ea1f875dbd4235df9bba83e8"}), "7daaed96e3db745587523fc034ecd1e5", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "StopAsync is called on the tunnel provider"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5cc5364bba7673558dcc3b8985c2999d"}), "229b9f7f7e833d50b6cd6785724d2520", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "no InvalidOperationException is thrown")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "c6dfc62814447b56897d3bc3eaf5c15a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("48c43cd07e96775987172cb5dafeb2fd", "Features/Tunnel/TunnelProviders.feature", "Tunnel process stop waits up to 5 seconds for graceful exit", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "02e95acd81323b55a50b711dad394db8"}), "6fb0c3d36dabd55dac07b6f38dde34da", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a tunnel provider has an active process"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e6061e453885aa58bdff235e3d264202"}), "e5eef37c24aff65b829b76d9930955cd", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "StopAsync is called"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "348b9b32c2b283548d4f88c92db2f19d"}), "76519e80f8809153beb14f0c05fc41a0", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the provider waits at most 5000 milliseconds for the process to exit")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "589770528d691656802177c0fcce9c91"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("9b681061b3960d5e80c925fc419bd6ad", "Features/Tunnel/TunnelProviders.feature", "FRP tunnel config file is deleted after stop", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "215f5128360d165398302238972d82c9"}), "4512a58c9f1c7e55bfe71da3b527b177", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the FrpTunnelProvider wrote a config file"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "93a60a1288ea145b81274ac691a644fb"}), "b9532d957d8a7556b51b086e825eccfc", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "StopAsync is called on the FrpTunnelProvider"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c4278df4d40e2555879db7d3df2354fb"}), "d044da9653739355bd92ac635a6b93ae", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the FRP config file should be deleted")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0fbac187c8a0d258983864355fd33a7d"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b15c2f0ab7a4cb549d5f28ac21172068", "Features/Tunnel/TunnelProviders.feature", "Tunnel provider is registered as IHostedService when provider name is set", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4b82a9bedeb13c5980e68b94f1aec139"}), "6eb5f9f0f02b0e54b2587ef7d52cfade", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "tunnel provider \"ngrok\" is configured"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1e886540f6841d5a87ec3ce6d5e63f07"}), "e4e9fb88214f0e50b87926c28aa5dbc5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the DI container should contain a registered IHostedService for the tunnel provid" +
                                                "er")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "aa3f225afbe3a25c88e0a69051ed8683"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b0b1ddc2a5ae645eb97cb8363b1cc26b", "Features/Tunnel/TunnelProviders.feature", "Cloudflare tunnel uses cloudflared quick tunnel when no named tunnel configured", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e98812e6829fb3559ccbdcf516f58a34"}), "655e0257e279fa5cb87b137577622ddd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the CloudflareTunnelProvider is configured without a tunnel name"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5888fed7dd1c2453b1e3473e0c4339c0"}), "753161222ec9275bae778bf203c81d26", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the CloudflareTunnelProvider builds its process start info"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5951a4631e88135e9184241652de1013"}), "95b185346c78f95a8dad27eaedba2697", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the process arguments should contain \"tunnel\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9e08065be2e2ca53bd83671902189537"}), "ae5f5ee6beb99654a81de2021de39221", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the process arguments should contain \"run\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "868ee42c2ddca252ac50c5ce6ff63f50"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(TunnelProvidersFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(TunnelProvidersFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(TunnelProvidersFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Ngrok tunnel provider uses NGROK_AUTHTOKEN environment variable")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tunnel Providers")]
        [global::Xunit.TraitAttribute("Description", "Ngrok tunnel provider uses NGROK_AUTHTOKEN environment variable")]
        public async global::System.Threading.Tasks.Task NgrokTunnelProviderUsesNGROK_AUTHTOKENEnvironmentVariable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ngrok tunnel provider uses NGROK_AUTHTOKEN environment variable", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
    await testRunner.GivenAsync("the NgrokTunnelProvider is configured with auth token \"test-token\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
    await testRunner.WhenAsync("the NgrokTunnelProvider builds its process start info", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("the process arguments should not contain the auth token", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("the environment variable \"NGROK_AUTHTOKEN\" should be set to \"test-token\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Tunnel process stop is TOCTOU-safe via try-catch on Process.Kill")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tunnel Providers")]
        [global::Xunit.TraitAttribute("Description", "Tunnel process stop is TOCTOU-safe via try-catch on Process.Kill")]
        public async global::System.Threading.Tasks.Task TunnelProcessStopIsTOCTOU_SafeViaTry_CatchOnProcess_Kill()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tunnel process stop is TOCTOU-safe via try-catch on Process.Kill", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("a tunnel process has already exited before StopAsync is called", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.WhenAsync("StopAsync is called on the tunnel provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("no InvalidOperationException is thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Tunnel process stop waits up to 5 seconds for graceful exit")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tunnel Providers")]
        [global::Xunit.TraitAttribute("Description", "Tunnel process stop waits up to 5 seconds for graceful exit")]
        public async global::System.Threading.Tasks.Task TunnelProcessStopWaitsUpTo5SecondsForGracefulExit()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tunnel process stop waits up to 5 seconds for graceful exit", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
    await testRunner.GivenAsync("a tunnel provider has an active process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 24
    await testRunner.WhenAsync("StopAsync is called", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("the provider waits at most 5000 milliseconds for the process to exit", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="FRP tunnel config file is deleted after stop")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tunnel Providers")]
        [global::Xunit.TraitAttribute("Description", "FRP tunnel config file is deleted after stop")]
        public async global::System.Threading.Tasks.Task FRPTunnelConfigFileIsDeletedAfterStop()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("FRP tunnel config file is deleted after stop", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
    await testRunner.GivenAsync("the FrpTunnelProvider wrote a config file", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
    await testRunner.WhenAsync("StopAsync is called on the FrpTunnelProvider", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the FRP config file should be deleted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Tunnel provider is registered as IHostedService when provider name is set")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tunnel Providers")]
        [global::Xunit.TraitAttribute("Description", "Tunnel provider is registered as IHostedService when provider name is set")]
        public async global::System.Threading.Tasks.Task TunnelProviderIsRegisteredAsIHostedServiceWhenProviderNameIsSet()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tunnel provider is registered as IHostedService when provider name is set", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("tunnel provider \"ngrok\" is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.ThenAsync("the DI container should contain a registered IHostedService for the tunnel provid" +
                        "er", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cloudflare tunnel uses cloudflared quick tunnel when no named tunnel configured")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Tunnel Providers")]
        [global::Xunit.TraitAttribute("Description", "Cloudflare tunnel uses cloudflared quick tunnel when no named tunnel configured")]
        public async global::System.Threading.Tasks.Task CloudflareTunnelUsesCloudflaredQuickTunnelWhenNoNamedTunnelConfigured()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cloudflare tunnel uses cloudflared quick tunnel when no named tunnel configured", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("the CloudflareTunnelProvider is configured without a tunnel name", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.WhenAsync("the CloudflareTunnelProvider builds its process start info", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("the process arguments should contain \"tunnel\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.AndAsync("the process arguments should contain \"run\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TunnelProvidersFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TunnelProvidersFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
