using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using McpServer.TransactionSecurity;
using McpServer.TransactionSecurity.Models;
using McpServer.TransactionSecurity.Options;
using Microsoft.Extensions.Options;

namespace McpServer.TransactionSecurity.Services;

/// <summary>FR-MCP-120: Coordinates manifest signing, mutation execution, and subscriber commit.</summary>
public interface ITurnTransactionCoordinator
{
    /// <summary>Executes a mutation under the configured transaction policy.</summary>
    /// <param name="request">Turn transaction metadata.</param>
    /// <param name="mutation">Mutation callback to execute after manifest signing succeeds.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Coordinator result.</returns>
    Task<TurnTransactionResult> ExecuteAsync(
        TurnTransactionRequest request,
        Func<CancellationToken, Task<TurnMutationResult>> mutation,
        CancellationToken cancellationToken = default);

    /// <summary>Gets the current coordinator status.</summary>
    /// <returns>Status response.</returns>
    TurnTransactionStatusResponse GetStatus();
}

/// <summary>FR-MCP-121: Applies degraded-mode policy for transaction dependency failures.</summary>
public interface ITransactionDegradedModePolicy
{
    /// <summary>Determines whether a failure should enter degraded mode.</summary>
    /// <param name="reason">Failure reason.</param>
    /// <returns><see langword="true"/> when degraded mode should be entered.</returns>
    bool ShouldEnterDegradedMode(TransactionFailureReason reason);
}

/// <summary>TR-MCP-TXNAUDIT-001: Captures transaction audit events.</summary>
public interface ITransactionAuditWriter
{
    /// <summary>Records a transaction audit event.</summary>
    /// <param name="eventName">Event name.</param>
    /// <param name="transactionId">Transaction identifier.</param>
    /// <param name="reason">Structured reason.</param>
    /// <param name="details">Optional detail message.</param>
    void Record(string eventName, string transactionId, TransactionFailureReason reason, string? details = null);

    /// <summary>Gets a snapshot of recorded audit events.</summary>
    /// <returns>Recorded audit events.</returns>
    IReadOnlyList<TransactionAuditEvent> Snapshot();
}

/// <summary>TR-MCP-TXN-001: Builds diffgram commit payloads for turn transactions.</summary>
public interface IDiffgramBuilder
{
    /// <summary>Builds plaintext and encrypted diffgram evidence for a turn transaction.</summary>
    /// <param name="request">Turn transaction request.</param>
    /// <param name="subscriberEncryptionKey">Optional subscriber public encryption key descriptor.</param>
    /// <returns>Diffgram payload.</returns>
    DiffgramPayload Build(TurnTransactionRequest request, PartyKeyDescriptor? subscriberEncryptionKey = null);
}

/// <summary>Transaction audit event captured by the in-memory audit writer. TR-MCP-TXNAUDIT-001.</summary>
public sealed class TransactionAuditEvent
{
    /// <summary>UTC event timestamp.</summary>
    public DateTimeOffset TimestampUtc { get; set; }

    /// <summary>Event name.</summary>
    public string EventName { get; set; } = string.Empty;

    /// <summary>Transaction identifier.</summary>
    public string TransactionId { get; set; } = string.Empty;

    /// <summary>Structured reason.</summary>
    public TransactionFailureReason Reason { get; set; }

    /// <summary>Optional detail message.</summary>
    public string? Details { get; set; }
}

/// <summary>Diffgram payload generated by an <see cref="IDiffgramBuilder"/>. TR-MCP-TXN-001.</summary>
public sealed class DiffgramPayload
{
    /// <summary>Plaintext diffgram JSON.</summary>
    public string PlaintextJson { get; set; } = string.Empty;

    /// <summary>Plaintext SHA-256 digest.</summary>
    public string PlaintextSha256 { get; set; } = string.Empty;

    /// <summary>Base64-encoded encrypted body or legacy placeholder body.</summary>
    public string EncryptedBodyBase64 { get; set; } = string.Empty;

    /// <summary>Encrypted body SHA-256 digest.</summary>
    public string EncryptedBodySha256 { get; set; } = string.Empty;

    /// <summary>Whether the encrypted body is a protected envelope.</summary>
    public bool IsProtectedEnvelope { get; set; }

    /// <summary>Subscriber encryption key identifier used to protect the envelope.</summary>
    public string? SubscriberEncryptionKeyId { get; set; }
}

/// <summary>FR-MCP-121: Options-backed degraded-mode policy.</summary>
public sealed class TransactionDegradedModePolicy : ITransactionDegradedModePolicy
{
    private readonly IOptionsMonitor<TurnTransactionOptions> _options;

    /// <summary>Initializes a new instance of the <see cref="TransactionDegradedModePolicy"/> class.</summary>
    /// <param name="options">Turn transaction options.</param>
    public TransactionDegradedModePolicy(IOptionsMonitor<TurnTransactionOptions> options)
    {
        _options = options;
    }

    /// <inheritdoc />
    public bool ShouldEnterDegradedMode(TransactionFailureReason reason)
        => _options.CurrentValue.DegradedModeEnabled &&
           reason is TransactionFailureReason.KeyServerUnavailable
               or TransactionFailureReason.SubscriberUnavailable
               or TransactionFailureReason.CommitTimeout
               or TransactionFailureReason.Unknown
               or TransactionFailureReason.TransactionsDisabled;
}

/// <summary>TR-MCP-TXNAUDIT-001: In-memory transaction audit writer.</summary>
public sealed class InMemoryTransactionAuditWriter : ITransactionAuditWriter
{
    private readonly object _gate = new();
    private readonly List<TransactionAuditEvent> _events = [];

    /// <inheritdoc />
    public void Record(string eventName, string transactionId, TransactionFailureReason reason, string? details = null)
    {
        lock (_gate)
        {
            _events.Add(new TransactionAuditEvent
            {
                TimestampUtc = DateTimeOffset.UtcNow,
                EventName = eventName,
                TransactionId = transactionId,
                Reason = reason,
                Details = details,
            });
        }
    }

    /// <inheritdoc />
    public IReadOnlyList<TransactionAuditEvent> Snapshot()
    {
        lock (_gate)
        {
            return _events
                .Select(item => new TransactionAuditEvent
                {
                    TimestampUtc = item.TimestampUtc,
                    EventName = item.EventName,
                    TransactionId = item.TransactionId,
                    Reason = item.Reason,
                    Details = item.Details,
                })
                .ToArray();
        }
    }
}

/// <summary>
/// Plain JSON body stored inside transaction diffgram evidence.
/// </summary>
internal sealed class TurnTransactionDiffgramBody
{
    /// <summary>Diffgram schema version.</summary>
    public int SchemaVersion { get; set; }

    /// <summary>Transaction identifier.</summary>
    public string? TransactionId { get; set; }

    /// <summary>Session-log turn identifier.</summary>
    public string? TurnId { get; set; }

    /// <summary>Operation name being committed.</summary>
    public string OperationName { get; set; } = string.Empty;

    /// <summary>Serialized operation body.</summary>
    public string OperationBodyJson { get; set; } = string.Empty;

    /// <summary>Transaction sequence number.</summary>
    public long Sequence { get; set; }

    /// <summary>UTC capture timestamp.</summary>
    public DateTimeOffset CapturedAtUtc { get; set; }
}

/// <summary>TR-MCP-TXN-001: JSON diffgram builder for coordinator evidence.</summary>
public sealed class JsonDiffgramBuilder : IDiffgramBuilder
{
    private readonly ITransactionDiffgramProtector _protector;

    /// <summary>Initializes a new instance of the <see cref="JsonDiffgramBuilder"/> class.</summary>
    /// <param name="protector">Diffgram protector used when a subscriber encryption key is supplied.</param>
    public JsonDiffgramBuilder(ITransactionDiffgramProtector? protector = null)
    {
        _protector = protector ?? new TransactionDiffgramProtector();
    }

    /// <inheritdoc />
    public DiffgramPayload Build(TurnTransactionRequest request, PartyKeyDescriptor? subscriberEncryptionKey = null)
    {
        ArgumentNullException.ThrowIfNull(request);
        var bodyPayload = new TurnTransactionDiffgramBody
        {
            SchemaVersion = 1,
            TransactionId = request.TransactionId,
            TurnId = request.TurnId,
            OperationName = request.OperationName,
            OperationBodyJson = request.OperationBodyJson,
            Sequence = request.Sequence,
            CapturedAtUtc = DateTimeOffset.UtcNow,
        };
        var body = JsonSerializer.Serialize(bodyPayload, typeof(TurnTransactionDiffgramBody), TransactionSecurityJsonContext.Default);
        if (subscriberEncryptionKey is not null)
        {
            var protectedDiffgram = _protector.Protect(body, subscriberEncryptionKey);
            return new DiffgramPayload
            {
                PlaintextJson = body,
                PlaintextSha256 = protectedDiffgram.PlaintextSha256,
                EncryptedBodyBase64 = protectedDiffgram.EncryptedDiffgramBase64,
                EncryptedBodySha256 = protectedDiffgram.EncryptedBodySha256,
                IsProtectedEnvelope = true,
                SubscriberEncryptionKeyId = subscriberEncryptionKey.KeyId,
            };
        }

        var encrypted = Convert.ToBase64String(Encoding.UTF8.GetBytes(body));
        return new DiffgramPayload
        {
            PlaintextJson = body,
            PlaintextSha256 = HashHex(Encoding.UTF8.GetBytes(body)),
            EncryptedBodyBase64 = encrypted,
            EncryptedBodySha256 = HashHex(Convert.FromBase64String(encrypted)),
            IsProtectedEnvelope = false,
        };
    }

    private static string HashHex(byte[] bytes)
        => Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
}

/// <summary>FR-MCP-120 and FR-MCP-121: In-process turn transaction coordinator.</summary>
public sealed class TurnTransactionCoordinator : ITurnTransactionCoordinator
{
    private readonly object _statusGate = new();
    private readonly IOptionsMonitor<TurnTransactionOptions> _options;
    private readonly IKeyServerPartyRegistry _partyRegistry;
    private readonly IKeyServerManifestService _keyServer;
    private readonly ITransactionPubSub _transactionPubSub;
    private readonly IDiffgramBuilder _diffgramBuilder;
    private readonly ITransactionDegradedModePolicy _degradedModePolicy;
    private readonly ITransactionAuditWriter _auditWriter;
    private readonly IOptionsMonitor<SubscriberOptions>? _subscriberOptions;
    private bool _degraded;
    private TransactionFailureReason _lastReason;
    private string? _lastTransactionId;

    /// <summary>Initializes a new instance of the <see cref="TurnTransactionCoordinator"/> class.</summary>
    /// <param name="options">Turn transaction options.</param>
    /// <param name="partyRegistry">Keyserver party registry.</param>
    /// <param name="keyServer">Keyserver manifest service.</param>
    /// <param name="transactionPubSub">Transaction pub-sub delivery seam.</param>
    /// <param name="diffgramBuilder">Diffgram builder.</param>
    /// <param name="degradedModePolicy">Degraded-mode policy.</param>
    /// <param name="auditWriter">Transaction audit writer.</param>
    /// <param name="subscriberOptions">Optional subscriber options used to mirror strict encryption configuration.</param>
    public TurnTransactionCoordinator(
        IOptionsMonitor<TurnTransactionOptions> options,
        IKeyServerPartyRegistry partyRegistry,
        IKeyServerManifestService keyServer,
        ITransactionPubSub transactionPubSub,
        IDiffgramBuilder diffgramBuilder,
        ITransactionDegradedModePolicy degradedModePolicy,
        ITransactionAuditWriter auditWriter,
        IOptionsMonitor<SubscriberOptions>? subscriberOptions = null)
    {
        _options = options;
        _partyRegistry = partyRegistry;
        _keyServer = keyServer;
        _transactionPubSub = transactionPubSub;
        _diffgramBuilder = diffgramBuilder;
        _degradedModePolicy = degradedModePolicy;
        _auditWriter = auditWriter;
        _subscriberOptions = subscriberOptions;
    }

    /// <inheritdoc />
    public async Task<TurnTransactionResult> ExecuteAsync(
        TurnTransactionRequest request,
        Func<CancellationToken, Task<TurnMutationResult>> mutation,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(mutation);
        cancellationToken.ThrowIfCancellationRequested();

        var options = _options.CurrentValue;
        var transactionId = NormalizeTransactionId(request.TransactionId);
        request.TransactionId = transactionId;
        request.PublisherPartyId = NormalizeParty(request.PublisherPartyId, options.PublisherPartyId);
        request.SubscriberPartyId = NormalizeParty(request.SubscriberPartyId, options.SubscriberPartyId);

        if (!request.Mutating || !options.Enabled || !options.RequiredForMutations)
        {
            var bypass = await mutation(cancellationToken).ConfigureAwait(false);
            var result = new TurnTransactionResult
            {
                TransactionId = transactionId,
                Status = "bypassed",
                Reason = TransactionFailureReason.None,
                MutationApplied = true,
                MutationResult = bypass,
                Degraded = GetStatus().Degraded,
                Message = GetBypassMessage(request, options),
            };
            RecordStatus(result);
            _auditWriter.Record("transaction_bypassed", transactionId, TransactionFailureReason.None, result.Message);
            return result;
        }

        var subscriberEncryptionKeyId = NormalizeSubscriberEncryptionKeyId(request.SubscriberPartyId!, options);
        await EnsureDefaultPartiesAsync(request.PublisherPartyId!, request.SubscriberPartyId!, subscriberEncryptionKeyId, cancellationToken)
            .ConfigureAwait(false);
        var subscriberEncryptionKey = await ResolveSubscriberEncryptionKeyAsync(
            request.SubscriberPartyId!,
            subscriberEncryptionKeyId,
            options,
            transactionId,
            cancellationToken).ConfigureAwait(false);
        if (ShouldProtectDiffgrams(options) && subscriberEncryptionKey is null)
            return Failure(transactionId, TransactionFailureReason.UnknownKey, "rejected", mutationApplied: false, message: "Subscriber encryption key was not available.");

        var diffgram = _diffgramBuilder.Build(request, subscriberEncryptionKey);
        var sign = await SignManifestAsync(request, diffgram, transactionId, cancellationToken).ConfigureAwait(false);
        if (!sign.Success || sign.Manifest is null)
            return Failure(transactionId, sign.Reason, "rejected", mutationApplied: false, message: "Keyserver manifest signing failed.");

        _auditWriter.Record("transaction_manifest_signed", transactionId, TransactionFailureReason.None);
        TurnMutationResult mutationResult;
        try
        {
            mutationResult = await mutation(cancellationToken).ConfigureAwait(false);
        }
        catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
        {
            mutationResult = new TurnMutationResult
            {
                Success = false,
                Error = ex.Message,
            };
        }

        if (!mutationResult.Success)
        {
            await _transactionPubSub.PublishAbortAsync(
                transactionId,
                new TransactionAbortRequest { Reason = TransactionFailureReason.Aborted, Actor = "TurnTransactionCoordinator" },
                cancellationToken).ConfigureAwait(false);
            var rollback = await RollbackMutationAsync(
                    transactionId,
                    mutationResult,
                    TransactionFailureReason.Aborted,
                    cancellationToken)
                .ConfigureAwait(false);
            await CancelPendingCommitAfterRollbackAsync(transactionId, rollback, cancellationToken)
                .ConfigureAwait(false);
            var result = new TurnTransactionResult
            {
                TransactionId = transactionId,
                Status = "aborted",
                Reason = TransactionFailureReason.Aborted,
                MutationApplied = true,
                MutationResult = mutationResult,
                Degraded = GetStatus().Degraded,
                Message = mutationResult.Error,
                RollbackAttempted = rollback.Attempted,
                RollbackSucceeded = rollback.Succeeded,
                RollbackError = rollback.Error,
            };
            RecordStatus(result);
            _auditWriter.Record("transaction_aborted", transactionId, TransactionFailureReason.Aborted, mutationResult.Error);
            return result;
        }

        var commit = await CommitDiffgramAsync(
            new DiffgramCommitRequest
            {
                Manifest = sign.Manifest,
                EncryptedDiffgramBase64 = diffgram.EncryptedBodyBase64,
                EncryptedBodySha256 = diffgram.EncryptedBodySha256,
                DiffgramSha256 = diffgram.PlaintextSha256,
            },
            options,
            transactionId,
            cancellationToken).ConfigureAwait(false);

        if (string.Equals(commit.Status, "committed", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(commit.Status, "duplicate", StringComparison.OrdinalIgnoreCase))
        {
            var result = new TurnTransactionResult
            {
                TransactionId = transactionId,
                Status = "committed",
                Reason = TransactionFailureReason.None,
                MutationApplied = true,
                MutationResult = mutationResult,
                Degraded = false,
                DiffgramId = commit.DiffgramId,
                Message = "Subscriber commit confirmed.",
            };
            RecordStatus(result);
            _auditWriter.Record("diffgram_committed", transactionId, TransactionFailureReason.None, commit.DiffgramId);
            return result;
        }

        var commitRollback = await RollbackMutationAsync(
                transactionId,
                mutationResult,
                commit.Reason,
                cancellationToken)
            .ConfigureAwait(false);
        await CancelPendingCommitAfterRollbackAsync(transactionId, commitRollback, cancellationToken)
            .ConfigureAwait(false);
        return Failure(
            transactionId,
            commit.Reason,
            "rejected",
            mutationApplied: true,
            mutationResult,
            "Subscriber commit failed.",
            commitRollback);
    }

    /// <inheritdoc />
    public TurnTransactionStatusResponse GetStatus()
    {
        lock (_statusGate)
        {
            return new TurnTransactionStatusResponse
            {
                Enabled = _options.CurrentValue.Enabled,
                Degraded = _degraded,
                LastReason = _lastReason,
                LastTransactionId = _lastTransactionId,
                Message = _degraded ? "Turn transactions are degraded." : "Turn transactions are available.",
            };
        }
    }

    private TurnTransactionResult Failure(
        string transactionId,
        TransactionFailureReason reason,
        string defaultStatus,
        bool mutationApplied,
        TurnMutationResult? mutationResult = null,
        string? message = null,
        TransactionRollbackResult rollback = default)
    {
        var degraded = _degradedModePolicy.ShouldEnterDegradedMode(reason);
        var result = new TurnTransactionResult
        {
            TransactionId = transactionId,
            Status = degraded ? "degraded" : defaultStatus,
            Reason = reason,
            MutationApplied = mutationApplied,
            MutationResult = mutationResult,
            Degraded = degraded,
            Message = message,
            RollbackAttempted = rollback.Attempted,
            RollbackSucceeded = rollback.Succeeded,
            RollbackError = rollback.Error,
        };
        RecordStatus(result);
        _auditWriter.Record(degraded ? "transaction_degraded" : "diffgram_rejected", transactionId, reason, message);
        return result;
    }

    private async Task<TransactionRollbackResult> RollbackMutationAsync(
        string transactionId,
        TurnMutationResult mutationResult,
        TransactionFailureReason reason,
        CancellationToken cancellationToken)
    {
        if (mutationResult.RollbackAsync is null)
            return default;

        try
        {
            await mutationResult.RollbackAsync(cancellationToken).ConfigureAwait(false);
            _auditWriter.Record("transaction_rollback_completed", transactionId, reason, "Mutation compensation completed.");
            return new TransactionRollbackResult(true, true, null);
        }
        catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
        {
            _auditWriter.Record("transaction_rollback_failed", transactionId, reason, ex.Message);
            return new TransactionRollbackResult(true, false, ex.Message);
        }
    }

    private async Task CancelPendingCommitAfterRollbackAsync(
        string transactionId,
        TransactionRollbackResult rollback,
        CancellationToken cancellationToken)
    {
        if (!rollback.Succeeded ||
            _transactionPubSub is not ITransactionPubSubCompensation compensation)
            return;

        try
        {
            await compensation.CancelPendingCommitAsync(
                    transactionId,
                    TransactionFailureReason.Aborted,
                    cancellationToken)
                .ConfigureAwait(false);
            _auditWriter.Record(
                "transaction_pending_commit_canceled",
                transactionId,
                TransactionFailureReason.Aborted,
                "Pending commit handoff canceled after rollback compensation.");
        }
        catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
        {
            _auditWriter.Record(
                "transaction_pending_commit_cancel_failed",
                transactionId,
                TransactionFailureReason.Aborted,
                ex.Message);
        }
    }

    private async Task<TransactionManifestSignResponse> SignManifestAsync(
        TurnTransactionRequest request,
        DiffgramPayload diffgram,
        string transactionId,
        CancellationToken cancellationToken)
    {
        try
        {
            return await _keyServer.SignManifestAsync(
                new TransactionManifestSignRequest
                {
                    TransactionId = transactionId,
                    TurnId = request.TurnId,
                    PublisherPartyId = request.PublisherPartyId!,
                    SubscriberPartyId = request.SubscriberPartyId!,
                    SubscriberEncryptionKeyId = diffgram.SubscriberEncryptionKeyId,
                    Sequence = request.Sequence,
                    Nonce = $"{transactionId}:{request.Sequence}",
                    DiffgramSha256 = diffgram.PlaintextSha256,
                    EncryptedBodySha256 = diffgram.EncryptedBodySha256,
                },
                cancellationToken).ConfigureAwait(false);
        }
        catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
        {
            _auditWriter.Record("diffgram_rejected", transactionId, TransactionFailureReason.KeyServerUnavailable, ex.Message);
            return new TransactionManifestSignResponse
            {
                Success = false,
                Reason = TransactionFailureReason.KeyServerUnavailable,
            };
        }
    }

    private async Task<DiffgramCommitResponse> CommitDiffgramAsync(
        DiffgramCommitRequest request,
        TurnTransactionOptions options,
        string transactionId,
        CancellationToken cancellationToken)
    {
        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        timeout.CancelAfter(TimeSpan.FromSeconds(Math.Max(1, options.CommitTimeoutSeconds)));

        try
        {
            return await _transactionPubSub.PublishCommitAsync(request, timeout.Token).ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (!cancellationToken.IsCancellationRequested)
        {
            return new DiffgramCommitResponse
            {
                TransactionId = transactionId,
                Status = "rejected",
                Reason = TransactionFailureReason.CommitTimeout,
            };
        }
        catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
        {
            _auditWriter.Record("diffgram_rejected", transactionId, TransactionFailureReason.SubscriberUnavailable, ex.Message);
            return new DiffgramCommitResponse
            {
                TransactionId = transactionId,
                Status = "rejected",
                Reason = TransactionFailureReason.SubscriberUnavailable,
            };
        }
    }

    private static string GetBypassMessage(TurnTransactionRequest request, TurnTransactionOptions options)
    {
        if (!options.Enabled)
            return "Turn transactions are disabled.";
        return request.Mutating
            ? "Turn transaction gating is enabled but not required for mutations."
            : "Read-only operation bypassed transaction gating.";
    }

    private void RecordStatus(TurnTransactionResult result)
    {
        lock (_statusGate)
        {
            _lastTransactionId = result.TransactionId;
            _lastReason = result.Reason;
            _degraded = result.Degraded;
        }
    }

    private async Task EnsureDefaultPartiesAsync(
        string publisherPartyId,
        string subscriberPartyId,
        string subscriberEncryptionKeyId,
        CancellationToken cancellationToken)
    {
        if (await _partyRegistry.GetPartyKeyAsync(publisherPartyId, $"{publisherPartyId}:signing:1", cancellationToken).ConfigureAwait(false) is null)
        {
            await _partyRegistry.RegisterPartyAsync(
                new PartyRegistrationRequest { PartyId = publisherPartyId, Role = "publisher" },
                cancellationToken).ConfigureAwait(false);
        }

        if (await _partyRegistry.GetPartyKeyAsync(subscriberPartyId, subscriberEncryptionKeyId, cancellationToken).ConfigureAwait(false) is null)
        {
            await _partyRegistry.RegisterPartyAsync(
                new PartyRegistrationRequest
                {
                    PartyId = subscriberPartyId,
                    Role = "subscriber",
                    ActiveEncryptionKeyId = subscriberEncryptionKeyId,
                },
                cancellationToken).ConfigureAwait(false);
        }
    }

    private async Task<PartyKeyDescriptor?> ResolveSubscriberEncryptionKeyAsync(
        string subscriberPartyId,
        string subscriberEncryptionKeyId,
        TurnTransactionOptions options,
        string transactionId,
        CancellationToken cancellationToken)
    {
        if (!ShouldProtectDiffgrams(options))
            return null;

        try
        {
            var key = await _partyRegistry.GetPartyKeyAsync(subscriberPartyId, subscriberEncryptionKeyId, cancellationToken)
                .ConfigureAwait(false);
            if (key is null)
                return null;
            if (!IsActive(key.Status) ||
                !string.Equals(key.Purpose, "encryption", StringComparison.OrdinalIgnoreCase) ||
                string.IsNullOrWhiteSpace(key.PublicKeyPem))
            {
                _auditWriter.Record("diffgram_rejected", transactionId, TransactionFailureReason.DisabledKey, subscriberEncryptionKeyId);
                return null;
            }

            return key;
        }
        catch (Exception ex) when (ex is not OperationCanceledException || !cancellationToken.IsCancellationRequested)
        {
            _auditWriter.Record("diffgram_rejected", transactionId, TransactionFailureReason.KeyServerUnavailable, ex.Message);
            return null;
        }
    }

    private static string NormalizeTransactionId(string? transactionId)
        => string.IsNullOrWhiteSpace(transactionId)
            ? $"txn-{Guid.NewGuid():N}"
            : transactionId.Trim();

    private static string NormalizeParty(string? requested, string fallback)
        => string.IsNullOrWhiteSpace(requested) ? fallback.Trim() : requested.Trim();

    private bool ShouldProtectDiffgrams(TurnTransactionOptions options)
        => options.ProtectDiffgrams || (_subscriberOptions?.CurrentValue.RequireEncryptedDiffgrams ?? false);

    private static string NormalizeSubscriberEncryptionKeyId(string subscriberPartyId, TurnTransactionOptions options)
        => string.IsNullOrWhiteSpace(options.SubscriberEncryptionKeyId)
            ? $"{subscriberPartyId}:encryption:1"
            : options.SubscriberEncryptionKeyId.Trim();

    private static bool IsActive(string? status)
        => string.IsNullOrWhiteSpace(status) || string.Equals(status, "active", StringComparison.OrdinalIgnoreCase);

    private readonly record struct TransactionRollbackResult(bool Attempted, bool Succeeded, string? Error);
}
