<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;Staging</Configurations>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <RootNamespace>McpServer.Subscriber</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\McpServer.ServiceDefaults\McpServer.ServiceDefaults.csproj" />
    <ProjectReference Include="..\McpServer.TransactionSecurity\McpServer.TransactionSecurity.csproj" />
  </ItemGroup>
</Project>
