// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace McpServer.SpecFlow.Tests.Features.Workspace
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PrimaryWorkspaceDetectionFeature : object, global::Xunit.IClassFixture<PrimaryWorkspaceDetectionFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Workspace", "Primary Workspace Detection", "  As the server host process\n  I want one workspace designated as the primary\n  S" +
                "o that its lifecycle is managed by the host process directly", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PrimaryWorkspace.feature"
#line hidden
        
        public PrimaryWorkspaceDetectionFeature(PrimaryWorkspaceDetectionFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the MCP server is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Workspace/PrimaryWorkspace.feature", "Feature: Primary Workspace Detection\n  As the server host process\n  I want one wo" +
                    "rkspace designated as the primary\n  So that its lifecycle is managed by the host" +
                    " process directly\n\n  Background:\n    Given the MCP server is running\n\n  # FR-MCP" +
                    "-025 / TR-MCP-WS-009\n\n  Scenario: Primary workspace prompt endpoint returns 200\n" +
                    "    When I send a GET request to \"/mcp/workspace/prompt\"\n    Then the response s" +
                    "tatus code is 200 or 403\n\n  Scenario: Primary workspace with IsPrimary flag true" +
                    " is served by the host process\n    When I send a GET request to \"/mcp/workspace\"" +
                    "\n    Then the response status code should be 200\n    And at most one workspace i" +
                    "n the result has \"isPrimary\" set to true\n\n  Scenario: Primary workspace status a" +
                    "lways returns isRunning\n    Given the primary workspace key is stored as \"primar" +
                    "yKey\"\n    When I send a GET request to \"/mcp/workspace/{primaryKey}/status\"\n    " +
                    "Then the response status code is 200 or 404\n\n  Scenario: Workspace auto-start sk" +
                    "ips disabled workspaces on startup\n    # Disabled workspaces have isEnabled = fa" +
                    "lse; they are logged as skipped\n    When I send a GET request to \"/mcp/workspace" +
                    "\"\n    Then the response status code should be 200\n    And the response body shou" +
                    "ld contain \"totalCount\"\n\n  Scenario: Workspace IsPrimary resolution uses lowest-" +
                    "port enabled workspace when none is flagged\n    # When no workspace has IsPrimar" +
                    "y=true, the enabled workspace with lowest port is primary\n    When I send a GET " +
                    "request to \"/mcp/workspace\"\n    Then the response status code should be 200\n\n  S" +
                    "cenario: WorkspaceController is excluded from workspace-scoped ports\n    # Works" +
                    "pace lifecycle endpoints are only on the primary host\n    Given I use a unique t" +
                    "emp directory stored as \"isolPath\"\n    And a workspace exists for path \"{isolPat" +
                    "h}\" with key stored as \"isolKey\"\n    And the workspace port is stored as \"isolPo" +
                    "rt\"\n    When I send a GET request to \"/mcp/workspace/{isolKey}/status\"\n    Then " +
                    "the response status code should be 200\n    And I delete the created workspace us" +
                    "ing the path \"{isolPath}\"\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Workspace/PrimaryWorkspace.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Primary Workspace Detection", "  As the server host process\n  I want one workspace designated as the primary\n  S" +
                        "o that its lifecycle is managed by the host process directly", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the MCP server is running", null, null, "cfc308bc7558845c8e4705e3719ba77a")}), "68a26ddbcc266b5dbabbcaa41eaaf557"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Primary workspace prompt endpoint returns 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/workspace/prompt\"", null, null, "b2103e4e136f18598e0ba4a43451389d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code is 200 or 403", null, null, "d9a6ec83db905b51a687fb91cef7b87c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ef63f9312cd7445795e3680a9caad2c0")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Primary workspace with IsPrimary flag true is served by the host process", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/workspace\"", null, null, "1e3df442c434225f8a255db99aae782c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "c4e0bb08c555355d980ce09ab6a3ca17"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "at most one workspace in the result has \"isPrimary\" set to true", null, null, "614561e80c155d52824680de1b7659e9")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "734d59d78f84805aa04f359d6c744634")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Primary workspace status always returns isRunning", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the primary workspace key is stored as \"primaryKey\"", null, null, "09da3d0704cd26558dea3c87489d4945"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/workspace/{primaryKey}/status\"", null, null, "816915890282f451a2f4761ce040e04c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code is 200 or 404", null, null, "c6edc9c45e61d255903042824a5f28f7")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3c4321a802d77152869a2c2795b594f6")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Workspace auto-start skips disabled workspaces on startup", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/workspace\"", null, null, "eeedc7fc84296c5c8afe9f4c46264c16"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "34932f3c93864452bb0d429dbeeac633"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response body should contain \"totalCount\"", null, null, "58287e164c25105ca091b0c2e255a9de")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "49045be24d6f2756880b06fb12875f97")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Workspace IsPrimary resolution uses lowest-port enabled workspace when none is fl" +
                                            "agged", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/workspace\"", null, null, "6b8bfee0286de852b115cf69d6b83f08"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "34e138aa7c1d31559eec9d734235d56d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0afc2871b54aa0559270f1cf25e48d8e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "WorkspaceController is excluded from workspace-scoped ports", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"isolPath\"", null, null, "56399f6ba1fa1e52ae3446fb8605009d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{isolPath}\" with key stored as \"isolKey\"", null, null, "c4d8c6643254c2559cad369aa11e667b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace port is stored as \"isolPort\"", null, null, "ab63da20102fd35088c4b96889807c72"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/workspace/{isolKey}/status\"", null, null, "f792a4e3ce377a59ad8c76a0e62ed4a1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "2a283d6aba33ff5da036249284bc8ed1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{isolPath}\"", null, null, "1deb1d5b9d218b5db77c128297e74d00")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f2c5992a9a879f568de8b39244e97b6e"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(1)), "  # FR-MCP-025 / TR-MCP-WS-009"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(1)), "    # Disabled workspaces have isEnabled = false; they are logged as skipped"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(1)), "    # When no workspace has IsPrimary=true, the enabled workspace with lowest por" +
                                    "t is primary"),
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(1)), "    # Workspace lifecycle endpoints are only on the primary host")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("7e59cdcef252d55b8a7dede528925b28", "Features/Workspace/PrimaryWorkspace.feature", "Primary workspace prompt endpoint returns 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cfc308bc7558845c8e4705e3719ba77a"}), "51c7fb7d51acb453b4d73f756782a41a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b2103e4e136f18598e0ba4a43451389d"}), "e11974c20d3215528788496b7f45f116", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/workspace/prompt\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d9a6ec83db905b51a687fb91cef7b87c"}), "6267fe752c2eec59ba73fc292d453281", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code is 200 or 403")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "ef63f9312cd7445795e3680a9caad2c0"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("69fb5a48f4c2475cb55142d69d9ba112", "Features/Workspace/PrimaryWorkspace.feature", "Primary workspace with IsPrimary flag true is served by the host process", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cfc308bc7558845c8e4705e3719ba77a"}), "6f534e37826e825ba1069b2664a0024e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1e3df442c434225f8a255db99aae782c"}), "4bafd13b66de925abdda8fb8062e435e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/workspace\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c4e0bb08c555355d980ce09ab6a3ca17"}), "8836fc92c61a84578a10650c622912e2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "614561e80c155d52824680de1b7659e9"}), "3a8eaf2017fb425fba56779555eb19ca", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "at most one workspace in the result has \"isPrimary\" set to true")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "734d59d78f84805aa04f359d6c744634"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("dbbb61d79cb6d55f96720fbd2c978903", "Features/Workspace/PrimaryWorkspace.feature", "Primary workspace status always returns isRunning", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cfc308bc7558845c8e4705e3719ba77a"}), "8d733c929e696259a3a258e2cbc66e3b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "09da3d0704cd26558dea3c87489d4945"}), "c72a3b0fbd41b9578d60b67654785539", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the primary workspace key is stored as \"primaryKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "816915890282f451a2f4761ce040e04c"}), "6b9941beb3770455867b001febff0a44", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/workspace/{primaryKey}/status\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c6edc9c45e61d255903042824a5f28f7"}), "0a7dd181843c8f549092c3629ccf909e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code is 200 or 404")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "3c4321a802d77152869a2c2795b594f6"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("14796b5c06aab4559b8c6debffd9465d", "Features/Workspace/PrimaryWorkspace.feature", "Workspace auto-start skips disabled workspaces on startup", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cfc308bc7558845c8e4705e3719ba77a"}), "867c2166a9d26051aedbe47f3840911a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "eeedc7fc84296c5c8afe9f4c46264c16"}), "0839e2a8a3178f5ca5de0ae0257fd3b3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/workspace\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "34932f3c93864452bb0d429dbeeac633"}), "7d45e0b5195af658aa189f81a6a85bbd", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "58287e164c25105ca091b0c2e255a9de"}), "35fcc25a1fbc805cafe0371cce0b90c6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response body should contain \"totalCount\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "49045be24d6f2756880b06fb12875f97"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1c37d230b9a25053ade185dcf253c8fa", "Features/Workspace/PrimaryWorkspace.feature", "Workspace IsPrimary resolution uses lowest-port enabled workspace when none is fl" +
                                "agged", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cfc308bc7558845c8e4705e3719ba77a"}), "8edbd2815aa12d5a80a6706208f8c241", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6b8bfee0286de852b115cf69d6b83f08"}), "b5881546fc3f025e86a77b994891c34a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/workspace\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "34e138aa7c1d31559eec9d734235d56d"}), "935131c8fe4b4e5fab283f4972c30c7d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0afc2871b54aa0559270f1cf25e48d8e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6da14b4c788eaa59922937a9a9eb2119", "Features/Workspace/PrimaryWorkspace.feature", "WorkspaceController is excluded from workspace-scoped ports", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cfc308bc7558845c8e4705e3719ba77a"}), "7c201c5c9aff3856a3559cdeba74d3dc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "56399f6ba1fa1e52ae3446fb8605009d"}), "65230027d5b4f650a613a054da76d2ba", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"isolPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c4d8c6643254c2559cad369aa11e667b"}), "0f63564d85b88e55ada70b802e56aafd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{isolPath}\" with key stored as \"isolKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab63da20102fd35088c4b96889807c72"}), "4286f3e868f77c55aabd4b2ff9095a04", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace port is stored as \"isolPort\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f792a4e3ce377a59ad8c76a0e62ed4a1"}), "65fb596a1bb377518975d105d386a9c0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/workspace/{isolKey}/status\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2a283d6aba33ff5da036249284bc8ed1"}), "9d69728e04f85b56982d0e90b8d5fead", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1deb1d5b9d218b5db77c128297e74d00"}), "650f22612b772656afefe1314b09e22f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{isolPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "f2c5992a9a879f568de8b39244e97b6e"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PrimaryWorkspaceDetectionFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PrimaryWorkspaceDetectionFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PrimaryWorkspaceDetectionFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Primary workspace prompt endpoint returns 200")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Primary Workspace Detection")]
        [global::Xunit.TraitAttribute("Description", "Primary workspace prompt endpoint returns 200")]
        public async global::System.Threading.Tasks.Task PrimaryWorkspacePromptEndpointReturns200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Primary workspace prompt endpoint returns 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("I send a GET request to \"/mcp/workspace/prompt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync("the response status code is 200 or 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Primary workspace with IsPrimary flag true is served by the host process")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Primary Workspace Detection")]
        [global::Xunit.TraitAttribute("Description", "Primary workspace with IsPrimary flag true is served by the host process")]
        public async global::System.Threading.Tasks.Task PrimaryWorkspaceWithIsPrimaryFlagTrueIsServedByTheHostProcess()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Primary workspace with IsPrimary flag true is served by the host process", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 16
    await testRunner.WhenAsync("I send a GET request to \"/mcp/workspace\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
    await testRunner.AndAsync("at most one workspace in the result has \"isPrimary\" set to true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Primary workspace status always returns isRunning")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Primary Workspace Detection")]
        [global::Xunit.TraitAttribute("Description", "Primary workspace status always returns isRunning")]
        public async global::System.Threading.Tasks.Task PrimaryWorkspaceStatusAlwaysReturnsIsRunning()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Primary workspace status always returns isRunning", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.GivenAsync("the primary workspace key is stored as \"primaryKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.WhenAsync("I send a GET request to \"/mcp/workspace/{primaryKey}/status\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
    await testRunner.ThenAsync("the response status code is 200 or 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Workspace auto-start skips disabled workspaces on startup")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Primary Workspace Detection")]
        [global::Xunit.TraitAttribute("Description", "Workspace auto-start skips disabled workspaces on startup")]
        public async global::System.Threading.Tasks.Task WorkspaceAuto_StartSkipsDisabledWorkspacesOnStartup()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workspace auto-start skips disabled workspaces on startup", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.WhenAsync("I send a GET request to \"/mcp/workspace\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
    await testRunner.AndAsync("the response body should contain \"totalCount\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Workspace IsPrimary resolution uses lowest-port enabled workspace when none is fl" +
            "agged")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Primary Workspace Detection")]
        [global::Xunit.TraitAttribute("Description", "Workspace IsPrimary resolution uses lowest-port enabled workspace when none is fl" +
            "agged")]
        public async global::System.Threading.Tasks.Task WorkspaceIsPrimaryResolutionUsesLowest_PortEnabledWorkspaceWhenNoneIsFlagged()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workspace IsPrimary resolution uses lowest-port enabled workspace when none is fl" +
                    "agged", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.WhenAsync("I send a GET request to \"/mcp/workspace\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="WorkspaceController is excluded from workspace-scoped ports")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Primary Workspace Detection")]
        [global::Xunit.TraitAttribute("Description", "WorkspaceController is excluded from workspace-scoped ports")]
        public async global::System.Threading.Tasks.Task WorkspaceControllerIsExcludedFromWorkspace_ScopedPorts()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("WorkspaceController is excluded from workspace-scoped ports", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("I use a unique temp directory stored as \"isolPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.AndAsync("a workspace exists for path \"{isolPath}\" with key stored as \"isolKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("the workspace port is stored as \"isolPort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.WhenAsync("I send a GET request to \"/mcp/workspace/{isolKey}/status\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
    await testRunner.AndAsync("I delete the created workspace using the path \"{isolPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PrimaryWorkspaceDetectionFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PrimaryWorkspaceDetectionFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
