// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace McpServer.SpecFlow.Tests.Features.Workspace
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WorkspaceMarkerFileAgentDiscoveryFeature : object, global::Xunit.IClassFixture<WorkspaceMarkerFileAgentDiscoveryFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Workspace", "Workspace Marker File Agent Discovery", "  As an AI agent\n  I want a marker file written to a workspace root when the host" +
                " starts\n  So that I can discover the correct server port and endpoints automatic" +
                "ally", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkspaceMarkerFile.feature"
#line hidden
        
        public WorkspaceMarkerFileAgentDiscoveryFeature(WorkspaceMarkerFileAgentDiscoveryFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the MCP server is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Workspace/WorkspaceMarkerFile.feature", "Feature: Workspace Marker File Agent Discovery\n  As an AI agent\n  I want a marker" +
                    " file written to a workspace root when the host starts\n  So that I can discover " +
                    "the correct server port and endpoints automatically\n\n  Background:\n    Given the" +
                    " MCP server is running\n\n  # FR-MCP-018 / TR-MCP-WS-005 / TEST-MCP-013\n\n  Scenari" +
                    "o: Workspace start writes AGENTS-README-FIRST.yaml to workspace root\n    Given I" +
                    " use a unique temp directory stored as \"markerWsPath\"\n    And a workspace exists" +
                    " for path \"{markerWsPath}\" with key stored as \"markerWsKey\"\n    When I POST to \"" +
                    "/mcp/workspace/{markerWsKey}/start\" with empty body\n    Then the response status" +
                    " code should be 200\n    And the file \"AGENTS-README-FIRST.yaml\" should exist in " +
                    "\"{markerWsPath}\"\n    And I stop the workspace \"{markerWsKey}\"\n    And I delete t" +
                    "he created workspace using the path \"{markerWsPath}\"\n\n  Scenario: Workspace stop" +
                    " removes the marker file\n    Given I use a unique temp directory stored as \"stop" +
                    "MarkerPath\"\n    And a workspace exists for path \"{stopMarkerPath}\" with key stor" +
                    "ed as \"stopMarkerKey\"\n    And the workspace \"{stopMarkerKey}\" is started\n    Whe" +
                    "n I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with empty body\n    Then the r" +
                    "esponse status code should be 200\n    And the file \"AGENTS-README-FIRST.yaml\" sh" +
                    "ould not exist in \"{stopMarkerPath}\"\n    And I delete the created workspace usin" +
                    "g the path \"{stopMarkerPath}\"\n\n  Scenario: Marker file contains the correct port" +
                    " number\n    Given I use a unique temp directory stored as \"portMarkerPath\"\n    A" +
                    "nd a workspace exists for path \"{portMarkerPath}\" with key stored as \"portMarker" +
                    "Key\" and port stored as \"wsPort\"\n    And the workspace \"{portMarkerKey}\" is star" +
                    "ted\n    Then the file \"AGENTS-README-FIRST.yaml\" in \"{portMarkerPath}\" should co" +
                    "ntain \"{wsPort}\"\n    And I stop the workspace \"{portMarkerKey}\"\n    And I delete" +
                    " the created workspace using the path \"{portMarkerPath}\"\n\n  Scenario: Marker fil" +
                    "e contains baseUrl field\n    Given I use a unique temp directory stored as \"base" +
                    "UrlMarkerPath\"\n    And a workspace exists for path \"{baseUrlMarkerPath}\" with ke" +
                    "y stored as \"baseUrlMarkerKey\"\n    And the workspace \"{baseUrlMarkerKey}\" is sta" +
                    "rted\n    Then the file \"AGENTS-README-FIRST.yaml\" in \"{baseUrlMarkerPath}\" shoul" +
                    "d contain \"baseUrl\"\n    And I stop the workspace \"{baseUrlMarkerKey}\"\n    And I " +
                    "delete the created workspace using the path \"{baseUrlMarkerPath}\"\n\n  Scenario: M" +
                    "arker file contains endpoint paths\n    Given I use a unique temp directory store" +
                    "d as \"endpointMarkerPath\"\n    And a workspace exists for path \"{endpointMarkerPa" +
                    "th}\" with key stored as \"endpointMarkerKey\"\n    And the workspace \"{endpointMark" +
                    "erKey}\" is started\n    Then the file \"AGENTS-README-FIRST.yaml\" in \"{endpointMar" +
                    "kerPath}\" should contain \"mcp/todo\"\n    And I stop the workspace \"{endpointMarke" +
                    "rKey}\"\n    And I delete the created workspace using the path \"{endpointMarkerPat" +
                    "h}\"\n\n  Scenario: Marker file contains machine-readable prompt block\n    Given I " +
                    "use a unique temp directory stored as \"promptMarkerPath\"\n    And a workspace exi" +
                    "sts for path \"{promptMarkerPath}\" with key stored as \"promptMarkerKey\"\n    And t" +
                    "he workspace \"{promptMarkerKey}\" is started\n    Then the file \"AGENTS-README-FIR" +
                    "ST.yaml\" in \"{promptMarkerPath}\" should contain \"prompt\"\n    And I stop the work" +
                    "space \"{promptMarkerKey}\"\n    And I delete the created workspace using the path " +
                    "\"{promptMarkerPath}\"\n\n  Scenario: Legacy .mcp-server.yaml files are cleaned up o" +
                    "n workspace stop\n    Given I use a unique temp directory stored as \"legacyMarker" +
                    "Path\"\n    And a legacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\"\n  " +
                    "  And a workspace exists for path \"{legacyMarkerPath}\" with key stored as \"legac" +
                    "yMarkerKey\"\n    When I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empt" +
                    "y body\n    Then the response status code should be 200\n    And the file \".mcp-se" +
                    "rver.yaml\" should not exist in \"{legacyMarkerPath}\"\n    And I delete the created" +
                    " workspace using the path \"{legacyMarkerPath}\"\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Workspace/WorkspaceMarkerFile.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Workspace Marker File Agent Discovery", "  As an AI agent\n  I want a marker file written to a workspace root when the host" +
                        " starts\n  So that I can discover the correct server port and endpoints automatic" +
                        "ally", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the MCP server is running", null, null, "72597e9f788b7a5088f38b7df4e555ed")}), "27a894aa7b338e5a9d241bb262edc889"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Workspace start writes AGENTS-README-FIRST.yaml to workspace root", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"markerWsPath\"", null, null, "e2f9634e1f8c8657bdad82f80dcda283"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{markerWsPath}\" with key stored as \"markerWsKey\"", null, null, "077c5fd3937a9a5d80822492806217d7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/workspace/{markerWsKey}/start\" with empty body", null, null, "e5c34a7726809e5da875b286b2375376"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "dc116d2ed01e8e57a041a2c644bcfaab"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the file \"AGENTS-README-FIRST.yaml\" should exist in \"{markerWsPath}\"", null, null, "1514d16b3545c65eb86370c58d422e72"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{markerWsKey}\"", null, null, "f7a1c5fe316c2159b97f1024f4ee2da4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{markerWsPath}\"", null, null, "299c31438636885fbe0b1ca496bf956b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2275b5a6eac84b58ad8b99c005fb3fbb")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Workspace stop removes the marker file", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"stopMarkerPath\"", null, null, "1028cd655c43cc59914259812bb0f351"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{stopMarkerPath}\" with key stored as \"stopMarkerKey\"" +
                                                            "", null, null, "93fd60a2261d8254ac4bad01e75a33d4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{stopMarkerKey}\" is started", null, null, "eef920911f247457a67dcf34971bc21a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with empty body", null, null, "166c62ea1efcaa5f8a3e44f17eed0cb6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "83eb8b221ff09d539de394a08b7610a8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the file \"AGENTS-README-FIRST.yaml\" should not exist in \"{stopMarkerPath}\"", null, null, "1193c3ce64b15c5386e2cb1b8450aa34"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{stopMarkerPath}\"", null, null, "9b6e1edca16d2e5fb74bf845555fc8d9")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6c94cba43551e15dbac23ed14d9b27b4")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains the correct port number", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"portMarkerPath\"", null, null, "9b4e15dc007fcc538e4ded7727e2b537"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{portMarkerPath}\" with key stored as \"portMarkerKey\"" +
                                                            " and port stored as \"wsPort\"", null, null, "c7475383337da151a201a61468df3d8f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{portMarkerKey}\" is started", null, null, "d7d23df80bd1ff529a8d988fbde74a80"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{portMarkerPath}\" should contain \"{wsPort" +
                                                            "}\"", null, null, "c12fc7be70f9ff5bb32adce0e2b3f4e4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{portMarkerKey}\"", null, null, "2acc2fc44a037251bf62b4f801fb2681"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{portMarkerPath}\"", null, null, "f384700deff1bf518f49e0564fb7dfc6")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a402f0a547cd6f5f9b3ba457dbd76b72")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains baseUrl field", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"baseUrlMarkerPath\"", null, null, "bc3919ec9011ab58881531d0a739e4cf"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{baseUrlMarkerPath}\" with key stored as \"baseUrlMark" +
                                                            "erKey\"", null, null, "ba9bb2a643e64c5981af3f10efb0ad0f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{baseUrlMarkerKey}\" is started", null, null, "e59869d31a67ff57b026edab315e1767"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{baseUrlMarkerPath}\" should contain \"base" +
                                                            "Url\"", null, null, "1647bddc3addc759b484f3b1d1b4e520"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{baseUrlMarkerKey}\"", null, null, "a1bc5cd52b5fe5558695cd148d0e8698"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{baseUrlMarkerPath}\"", null, null, "a7c627c761dbec5596a93d739e3ecc5d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "c014f90f5ec54f51a779aba4913f9b4d")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains endpoint paths", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"endpointMarkerPath\"", null, null, "c496d29e61f0ec5c9fb052046799e485"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{endpointMarkerPath}\" with key stored as \"endpointMa" +
                                                            "rkerKey\"", null, null, "748dfeab5a79af58bff069d6bd66d7f5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{endpointMarkerKey}\" is started", null, null, "366b5b340f45e654b739a71463b9be33"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{endpointMarkerPath}\" should contain \"mcp" +
                                                            "/todo\"", null, null, "5b411fd989596052b01588c5cbbd8e82"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{endpointMarkerKey}\"", null, null, "2fafc6eb13c1135588ea9e241f8a10d1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{endpointMarkerPath}\"", null, null, "c1eead4915f6e55a8a4d7c837f215428")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f4303288495c3051b464a915912e0e85")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains machine-readable prompt block", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"promptMarkerPath\"", null, null, "1cff7b551e552a53b6b12bfcfd8277f8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{promptMarkerPath}\" with key stored as \"promptMarker" +
                                                            "Key\"", null, null, "75ee797d3866f758bc56e9d53a70c9b8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{promptMarkerKey}\" is started", null, null, "0c0bcf6e83a8ad5aa251f66980f196df"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{promptMarkerPath}\" should contain \"promp" +
                                                            "t\"", null, null, "9e14b8012fdf8759a67b462cc75b3fac"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{promptMarkerKey}\"", null, null, "a29773ddae67755ab423dd7958c0b975"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{promptMarkerPath}\"", null, null, "fc3c1012bc77f5508d0bf24a5368e650")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "768e62f42a2b4f5686c3abd6b6f18028")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Legacy .mcp-server.yaml files are cleaned up on workspace stop", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"legacyMarkerPath\"", null, null, "bc114fcbb3e46d5c8136aaeac39213ca"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a legacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\"", null, null, "6fb309ae51a1b550b9348d532f6a16ca"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{legacyMarkerPath}\" with key stored as \"legacyMarker" +
                                                            "Key\"", null, null, "e0141e0e425ed15cbfc958ba2def7436"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(65, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empty body", null, null, "d5994a79504c2759aec5f854301a03cc"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "5cb8beacb3abe85cb67314a44c1d643e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(67, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the file \".mcp-server.yaml\" should not exist in \"{legacyMarkerPath}\"", null, null, "769ff0041eb2ac5fb3b7cf0d638fe2f4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(68, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{legacyMarkerPath}\"", null, null, "e246a907af5df95bba29bd2c226c6e6b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "9b6e47d18413f45abafff5f4daf5aec5"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(1)), "  # FR-MCP-018 / TR-MCP-WS-005 / TEST-MCP-013")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("2d4331c7eb82f750be2152158def25d8", "Features/Workspace/WorkspaceMarkerFile.feature", "Workspace start writes AGENTS-README-FIRST.yaml to workspace root", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "72597e9f788b7a5088f38b7df4e555ed"}), "9ae17490d964535caca6e588d57705e9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e2f9634e1f8c8657bdad82f80dcda283"}), "c969295409e95959ab1b6b7c5fdff6fb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"markerWsPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "077c5fd3937a9a5d80822492806217d7"}), "8e3f6ddff6dc0451b35c00fd15d75a9b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{markerWsPath}\" with key stored as \"markerWsKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e5c34a7726809e5da875b286b2375376"}), "a0b86c4d2122fe54963110373afc709c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/workspace/{markerWsKey}/start\" with empty body"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "dc116d2ed01e8e57a041a2c644bcfaab"}), "fdcc8aa59b4b7c50bf99b0095aa0bca4", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1514d16b3545c65eb86370c58d422e72"}), "e8a51600a608415a82ec421ecb10b623", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" should exist in \"{markerWsPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f7a1c5fe316c2159b97f1024f4ee2da4"}), "3ce0255f52c2f651ab1d27479a858834", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{markerWsKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "299c31438636885fbe0b1ca496bf956b"}), "b93c5cdd8bbd68588bda5e429250e79c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{markerWsPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "2275b5a6eac84b58ad8b99c005fb3fbb"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3819abbb3c765858b2b676c9d1021052", "Features/Workspace/WorkspaceMarkerFile.feature", "Workspace stop removes the marker file", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "72597e9f788b7a5088f38b7df4e555ed"}), "bd13528f1633285682f3dcec489ee4d6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1028cd655c43cc59914259812bb0f351"}), "069b292f14658756af9dd6630f36c713", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"stopMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "93fd60a2261d8254ac4bad01e75a33d4"}), "252c286f89779c538236f732208866cb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{stopMarkerPath}\" with key stored as \"stopMarkerKey\"" +
                                                ""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "eef920911f247457a67dcf34971bc21a"}), "a30570b0df5b1e57843f4db4904aa5c9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{stopMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "166c62ea1efcaa5f8a3e44f17eed0cb6"}), "1ccdf8f513911552be372539c538f86f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with empty body"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "83eb8b221ff09d539de394a08b7610a8"}), "aa331803c16b9c528fb812cb6f959b22", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1193c3ce64b15c5386e2cb1b8450aa34"}), "25d548c20d8a0053b41256d804816b55", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" should not exist in \"{stopMarkerPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9b6e1edca16d2e5fb74bf845555fc8d9"}), "a771f34e983e4250b914fded4499fb9d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{stopMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6c94cba43551e15dbac23ed14d9b27b4"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("32fa7e1a5bab4653b5cd201c3c6bd529", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains the correct port number", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "72597e9f788b7a5088f38b7df4e555ed"}), "e610fef8c0736851b424b79e14c245d3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9b4e15dc007fcc538e4ded7727e2b537"}), "7a5a4d7282c5bc55a7611dee4a12ff9e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"portMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c7475383337da151a201a61468df3d8f"}), "355360f8b178f9519dd3a3c1f75c66ed", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{portMarkerPath}\" with key stored as \"portMarkerKey\"" +
                                                " and port stored as \"wsPort\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d7d23df80bd1ff529a8d988fbde74a80"}), "ce2bca95a052f3518f98cc24f490be1f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{portMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c12fc7be70f9ff5bb32adce0e2b3f4e4"}), "5d1364a7be5f495b928f17f9c42764e5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{portMarkerPath}\" should contain \"{wsPort" +
                                                "}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2acc2fc44a037251bf62b4f801fb2681"}), "fe8490b82c72d257bb77c8a87a978abc", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{portMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f384700deff1bf518f49e0564fb7dfc6"}), "4908e196f2a0f151990a17fa0a5e38b9", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{portMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "a402f0a547cd6f5f9b3ba457dbd76b72"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("2f93ce8c07255b57b0ff5e13dbbad6c7", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains baseUrl field", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "72597e9f788b7a5088f38b7df4e555ed"}), "86a3ed5652a5af57a66ffc80a8bf892a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bc3919ec9011ab58881531d0a739e4cf"}), "0514ddf4611c0c57904a0b42bc1c1c24", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"baseUrlMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ba9bb2a643e64c5981af3f10efb0ad0f"}), "b1944976812adf53a7a0da3fe0b30cdb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{baseUrlMarkerPath}\" with key stored as \"baseUrlMark" +
                                                "erKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e59869d31a67ff57b026edab315e1767"}), "b42855ed03bd0b51a77be21716307d49", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{baseUrlMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1647bddc3addc759b484f3b1d1b4e520"}), "d9337f9f910e0f5daf70a13250dad37d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{baseUrlMarkerPath}\" should contain \"base" +
                                                "Url\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a1bc5cd52b5fe5558695cd148d0e8698"}), "4c6ded1e43925f558a05f6532f8ece47", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{baseUrlMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a7c627c761dbec5596a93d739e3ecc5d"}), "66e4fa8af178295daab976bd88838b5d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{baseUrlMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "c014f90f5ec54f51a779aba4913f9b4d"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("745a1a7742d9e45ebf1e4781333444e4", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains endpoint paths", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "72597e9f788b7a5088f38b7df4e555ed"}), "b2cc17a247ded551859dc0c11dac4aa3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c496d29e61f0ec5c9fb052046799e485"}), "35cea3176ae9d05195b58a13680a9639", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"endpointMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "748dfeab5a79af58bff069d6bd66d7f5"}), "e734fa23c983ee5cad15a5241cc3969d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{endpointMarkerPath}\" with key stored as \"endpointMa" +
                                                "rkerKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "366b5b340f45e654b739a71463b9be33"}), "c8fb2a2bb5b5b75e8bef5b248fa5023e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{endpointMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5b411fd989596052b01588c5cbbd8e82"}), "9ddda506313859539c27bd38e2a415b5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{endpointMarkerPath}\" should contain \"mcp" +
                                                "/todo\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2fafc6eb13c1135588ea9e241f8a10d1"}), "15d1d01e9632d657aee49d2d6c226ae7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{endpointMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c1eead4915f6e55a8a4d7c837f215428"}), "6ddb5c69fd94e65e8236c84c3c965cb8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{endpointMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "f4303288495c3051b464a915912e0e85"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b9a4c807fad31e57a6a49b30fc09b202", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains machine-readable prompt block", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "72597e9f788b7a5088f38b7df4e555ed"}), "1ca03a3e2d33e850b4e084ee19a167d8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1cff7b551e552a53b6b12bfcfd8277f8"}), "b02388cc92c8125c92ec3e2207048f43", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"promptMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "75ee797d3866f758bc56e9d53a70c9b8"}), "85c290010159ca5caee0d7b96d6640a5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{promptMarkerPath}\" with key stored as \"promptMarker" +
                                                "Key\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0c0bcf6e83a8ad5aa251f66980f196df"}), "e6aded0d2e0d79519e0447b4e1af5865", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{promptMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9e14b8012fdf8759a67b462cc75b3fac"}), "0e8747264eeca35292c0104eb7c1ff43", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{promptMarkerPath}\" should contain \"promp" +
                                                "t\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a29773ddae67755ab423dd7958c0b975"}), "11507529a9c6795986e4a64f87014cce", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{promptMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fc3c1012bc77f5508d0bf24a5368e650"}), "dab439ff470eba50bb0ee8a0333193f0", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{promptMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "768e62f42a2b4f5686c3abd6b6f18028"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("9c1c7d7e257b70589873ef50b43ce462", "Features/Workspace/WorkspaceMarkerFile.feature", "Legacy .mcp-server.yaml files are cleaned up on workspace stop", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "72597e9f788b7a5088f38b7df4e555ed"}), "bc57b7e0238d2a569fc17cf78aa52fab", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bc114fcbb3e46d5c8136aaeac39213ca"}), "95d2f79b2eed1f53b0272eb798ca9cb0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"legacyMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6fb309ae51a1b550b9348d532f6a16ca"}), "516688c5e07c0f538643b1a9ce02cf0c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a legacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e0141e0e425ed15cbfc958ba2def7436"}), "5008f7e68ff91f50967fb1e687e95863", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{legacyMarkerPath}\" with key stored as \"legacyMarker" +
                                                "Key\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d5994a79504c2759aec5f854301a03cc"}), "18e36192eeef3551a0edb27c67f4cca1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empty body"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5cb8beacb3abe85cb67314a44c1d643e"}), "c57a5bb891ba8453a1a8b96c33ce2ec3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "769ff0041eb2ac5fb3b7cf0d638fe2f4"}), "0a65fe70d6fbe65db5bc25c25a53310a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \".mcp-server.yaml\" should not exist in \"{legacyMarkerPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e246a907af5df95bba29bd2c226c6e6b"}), "e66bbc6cb191455ab78138588469c500", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{legacyMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "9b6e47d18413f45abafff5f4daf5aec5"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(WorkspaceMarkerFileAgentDiscoveryFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(WorkspaceMarkerFileAgentDiscoveryFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(WorkspaceMarkerFileAgentDiscoveryFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Workspace start writes AGENTS-README-FIRST.yaml to workspace root")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Workspace start writes AGENTS-README-FIRST.yaml to workspace root")]
        public async global::System.Threading.Tasks.Task WorkspaceStartWritesAGENTS_README_FIRST_YamlToWorkspaceRoot()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workspace start writes AGENTS-README-FIRST.yaml to workspace root", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.GivenAsync("I use a unique temp directory stored as \"markerWsPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
    await testRunner.AndAsync("a workspace exists for path \"{markerWsPath}\" with key stored as \"markerWsKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.WhenAsync("I POST to \"/mcp/workspace/{markerWsKey}/start\" with empty body", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
    await testRunner.AndAsync("the file \"AGENTS-README-FIRST.yaml\" should exist in \"{markerWsPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("I stop the workspace \"{markerWsKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("I delete the created workspace using the path \"{markerWsPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Workspace stop removes the marker file")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Workspace stop removes the marker file")]
        public async global::System.Threading.Tasks.Task WorkspaceStopRemovesTheMarkerFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workspace stop removes the marker file", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.GivenAsync("I use a unique temp directory stored as \"stopMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.AndAsync("a workspace exists for path \"{stopMarkerPath}\" with key stored as \"stopMarkerKey\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("the workspace \"{stopMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.WhenAsync("I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with empty body", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.AndAsync("the file \"AGENTS-README-FIRST.yaml\" should not exist in \"{stopMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("I delete the created workspace using the path \"{stopMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains the correct port number")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains the correct port number")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsTheCorrectPortNumber()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains the correct port number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("I use a unique temp directory stored as \"portMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.AndAsync("a workspace exists for path \"{portMarkerPath}\" with key stored as \"portMarkerKey\"" +
                        " and port stored as \"wsPort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("the workspace \"{portMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{portMarkerPath}\" should contain \"{wsPort" +
                        "}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
    await testRunner.AndAsync("I stop the workspace \"{portMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync("I delete the created workspace using the path \"{portMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains baseUrl field")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains baseUrl field")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsBaseUrlField()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains baseUrl field", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("I use a unique temp directory stored as \"baseUrlMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.AndAsync("a workspace exists for path \"{baseUrlMarkerPath}\" with key stored as \"baseUrlMark" +
                        "erKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("the workspace \"{baseUrlMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{baseUrlMarkerPath}\" should contain \"base" +
                        "Url\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.AndAsync("I stop the workspace \"{baseUrlMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.AndAsync("I delete the created workspace using the path \"{baseUrlMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains endpoint paths")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains endpoint paths")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsEndpointPaths()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains endpoint paths", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("I use a unique temp directory stored as \"endpointMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.AndAsync("a workspace exists for path \"{endpointMarkerPath}\" with key stored as \"endpointMa" +
                        "rkerKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.AndAsync("the workspace \"{endpointMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{endpointMarkerPath}\" should contain \"mcp" +
                        "/todo\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("I stop the workspace \"{endpointMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("I delete the created workspace using the path \"{endpointMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains machine-readable prompt block")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains machine-readable prompt block")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsMachine_ReadablePromptBlock()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains machine-readable prompt block", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.GivenAsync("I use a unique temp directory stored as \"promptMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
    await testRunner.AndAsync("a workspace exists for path \"{promptMarkerPath}\" with key stored as \"promptMarker" +
                        "Key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.AndAsync("the workspace \"{promptMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{promptMarkerPath}\" should contain \"promp" +
                        "t\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("I stop the workspace \"{promptMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("I delete the created workspace using the path \"{promptMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Legacy .mcp-server.yaml files are cleaned up on workspace stop")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Legacy .mcp-server.yaml files are cleaned up on workspace stop")]
        public async global::System.Threading.Tasks.Task Legacy_Mcp_Server_YamlFilesAreCleanedUpOnWorkspaceStop()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Legacy .mcp-server.yaml files are cleaned up on workspace stop", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
    await testRunner.GivenAsync("I use a unique temp directory stored as \"legacyMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
    await testRunner.AndAsync("a legacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("a workspace exists for path \"{legacyMarkerPath}\" with key stored as \"legacyMarker" +
                        "Key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.WhenAsync("I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empty body", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
    await testRunner.AndAsync("the file \".mcp-server.yaml\" should not exist in \"{legacyMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("I delete the created workspace using the path \"{legacyMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WorkspaceMarkerFileAgentDiscoveryFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WorkspaceMarkerFileAgentDiscoveryFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
