// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace McpServer.SpecFlow.Tests.Features.Workspace
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WorkspaceMarkerFileAgentDiscoveryFeature : object, global::Xunit.IClassFixture<WorkspaceMarkerFileAgentDiscoveryFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Workspace", "Workspace Marker File Agent Discovery", "  As an AI agent\r\n  I want a marker file written to a workspace root when the hos" +
                "t starts\r\n  So that I can discover the correct server port and endpoints automat" +
                "ically", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkspaceMarkerFile.feature"
#line hidden
        
        public WorkspaceMarkerFileAgentDiscoveryFeature(WorkspaceMarkerFileAgentDiscoveryFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the MCP server is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Workspace/WorkspaceMarkerFile.feature", "Feature: Workspace Marker File Agent Discovery\r\n  As an AI agent\r\n  I want a mark" +
                    "er file written to a workspace root when the host starts\r\n  So that I can discov" +
                    "er the correct server port and endpoints automatically\r\n\r\n  Background:\r\n    Giv" +
                    "en the MCP server is running\r\n\r\n  # FR-MCP-018 / TR-MCP-WS-005 / TEST-MCP-013\r\n\r" +
                    "\n  Scenario: Workspace start writes AGENTS-README-FIRST.yaml to workspace root\r\n" +
                    "    Given I use a unique temp directory stored as \"markerWsPath\"\r\n    And a work" +
                    "space exists for path \"{markerWsPath}\" with key stored as \"markerWsKey\"\r\n    Whe" +
                    "n I POST to \"/mcp/workspace/{markerWsKey}/start\" with empty body\r\n    Then the r" +
                    "esponse status code should be 200\r\n    And the file \"AGENTS-README-FIRST.yaml\" s" +
                    "hould exist in \"{markerWsPath}\"\r\n    And I stop the workspace \"{markerWsKey}\"\r\n " +
                    "   And I delete the created workspace using the path \"{markerWsPath}\"\r\n\r\n  Scena" +
                    "rio: Workspace stop removes the marker file\r\n    Given I use a unique temp direc" +
                    "tory stored as \"stopMarkerPath\"\r\n    And a workspace exists for path \"{stopMarke" +
                    "rPath}\" with key stored as \"stopMarkerKey\"\r\n    And the workspace \"{stopMarkerKe" +
                    "y}\" is started\r\n    When I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with em" +
                    "pty body\r\n    Then the response status code should be 200\r\n    And the file \"AGE" +
                    "NTS-README-FIRST.yaml\" should not exist in \"{stopMarkerPath}\"\r\n    And I delete " +
                    "the created workspace using the path \"{stopMarkerPath}\"\r\n\r\n  Scenario: Marker fi" +
                    "le contains the correct port number\r\n    Given I use a unique temp directory sto" +
                    "red as \"portMarkerPath\"\r\n    And a workspace exists for path \"{portMarkerPath}\" " +
                    "with key stored as \"portMarkerKey\" and port stored as \"wsPort\"\r\n    And the work" +
                    "space \"{portMarkerKey}\" is started\r\n    Then the file \"AGENTS-README-FIRST.yaml\"" +
                    " in \"{portMarkerPath}\" should contain \"{wsPort}\"\r\n    And I stop the workspace \"" +
                    "{portMarkerKey}\"\r\n    And I delete the created workspace using the path \"{portMa" +
                    "rkerPath}\"\r\n\r\n  Scenario: Marker file contains baseUrl field\r\n    Given I use a " +
                    "unique temp directory stored as \"baseUrlMarkerPath\"\r\n    And a workspace exists " +
                    "for path \"{baseUrlMarkerPath}\" with key stored as \"baseUrlMarkerKey\"\r\n    And th" +
                    "e workspace \"{baseUrlMarkerKey}\" is started\r\n    Then the file \"AGENTS-README-FI" +
                    "RST.yaml\" in \"{baseUrlMarkerPath}\" should contain \"baseUrl\"\r\n    And I stop the " +
                    "workspace \"{baseUrlMarkerKey}\"\r\n    And I delete the created workspace using the" +
                    " path \"{baseUrlMarkerPath}\"\r\n\r\n  Scenario: Marker file contains endpoint paths\r\n" +
                    "    Given I use a unique temp directory stored as \"endpointMarkerPath\"\r\n    And " +
                    "a workspace exists for path \"{endpointMarkerPath}\" with key stored as \"endpointM" +
                    "arkerKey\"\r\n    And the workspace \"{endpointMarkerKey}\" is started\r\n    Then the " +
                    "file \"AGENTS-README-FIRST.yaml\" in \"{endpointMarkerPath}\" should contain \"mcp/to" +
                    "do\"\r\n    And I stop the workspace \"{endpointMarkerKey}\"\r\n    And I delete the cr" +
                    "eated workspace using the path \"{endpointMarkerPath}\"\r\n\r\n  Scenario: Marker file" +
                    " contains machine-readable prompt block\r\n    Given I use a unique temp directory" +
                    " stored as \"promptMarkerPath\"\r\n    And a workspace exists for path \"{promptMarke" +
                    "rPath}\" with key stored as \"promptMarkerKey\"\r\n    And the workspace \"{promptMark" +
                    "erKey}\" is started\r\n    Then the file \"AGENTS-README-FIRST.yaml\" in \"{promptMark" +
                    "erPath}\" should contain \"prompt\"\r\n    And I stop the workspace \"{promptMarkerKey" +
                    "}\"\r\n    And I delete the created workspace using the path \"{promptMarkerPath}\"\r\n" +
                    "\r\n  Scenario: Legacy .mcp-server.yaml files are cleaned up on workspace stop\r\n  " +
                    "  Given I use a unique temp directory stored as \"legacyMarkerPath\"\r\n    And a le" +
                    "gacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\"\r\n    And a workspace" +
                    " exists for path \"{legacyMarkerPath}\" with key stored as \"legacyMarkerKey\"\r\n    " +
                    "When I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empty body\r\n    Then" +
                    " the response status code should be 200\r\n    And the file \".mcp-server.yaml\" sho" +
                    "uld not exist in \"{legacyMarkerPath}\"\r\n    And I delete the created workspace us" +
                    "ing the path \"{legacyMarkerPath}\"\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Workspace/WorkspaceMarkerFile.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Workspace Marker File Agent Discovery", "  As an AI agent\r\n  I want a marker file written to a workspace root when the hos" +
                        "t starts\r\n  So that I can discover the correct server port and endpoints automat" +
                        "ically", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the MCP server is running", null, null, "cc2c402017a109588cfa217bdd4b1987")}), "da794b49f8628955a721288a353fba7d"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Workspace start writes AGENTS-README-FIRST.yaml to workspace root", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"markerWsPath\"", null, null, "2f9f7a64f872ac5a98aa109e4dfd65c4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{markerWsPath}\" with key stored as \"markerWsKey\"", null, null, "4a39ae1dd1c2415e8eef71e20301256d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/workspace/{markerWsKey}/start\" with empty body", null, null, "d7f0b1132b0dd850a39dfe89cb6b2197"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "945c90c1ef4994529a54651c90e16f55"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the file \"AGENTS-README-FIRST.yaml\" should exist in \"{markerWsPath}\"", null, null, "0d2f93088e67725db5fa8b5dd31a2dea"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{markerWsKey}\"", null, null, "f78d35e6c32b4f5ca40254d8fbce24db"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{markerWsPath}\"", null, null, "047355b1ec8ad75095e716bc10839e79")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6bd7a992582f8756865e3454266d06b2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Workspace stop removes the marker file", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"stopMarkerPath\"", null, null, "05a700a8edd6eb5fa361b353bf85a49a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{stopMarkerPath}\" with key stored as \"stopMarkerKey\"" +
                                                            "", null, null, "0dbe9883e98cce52ac6e3c043523ba07"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{stopMarkerKey}\" is started", null, null, "0c797d0117ac14538db84a93c77bc965"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with empty body", null, null, "d8a331919980e55fa824853f6c2e67b6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "2ead7c5aea63b05c8e917a2816e7c243"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the file \"AGENTS-README-FIRST.yaml\" should not exist in \"{stopMarkerPath}\"", null, null, "b7f6e96b7d4ce352a8a223f6f7fff0b7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{stopMarkerPath}\"", null, null, "c229d4540c5261509b9b3f6de2016b82")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "519e90289818175083cb77a7d6c91b0e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains the correct port number", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"portMarkerPath\"", null, null, "07da4fd25dba1652a35dd84dfdabc6d7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{portMarkerPath}\" with key stored as \"portMarkerKey\"" +
                                                            " and port stored as \"wsPort\"", null, null, "e68ceb8675d8dd5f8b53b40311979e2f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{portMarkerKey}\" is started", null, null, "ae649483f0ccdd5dbe8fa244b16ef85a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{portMarkerPath}\" should contain \"{wsPort" +
                                                            "}\"", null, null, "f60be18cc9c53b58b80ea3cd6fe06e4f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{portMarkerKey}\"", null, null, "50bd496f5ab39357b95c4885b4a04d06"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{portMarkerPath}\"", null, null, "6b06cf8e76453b558889e82e3cd37acb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "707640aaa283bd5e91d598527724da7a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains baseUrl field", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"baseUrlMarkerPath\"", null, null, "f1498531ee53325d8eb7598fd420bea4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{baseUrlMarkerPath}\" with key stored as \"baseUrlMark" +
                                                            "erKey\"", null, null, "f3a9f62f76066d55bb9719098b0db8fa"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{baseUrlMarkerKey}\" is started", null, null, "3e4a794a17abc3578a94925b094db27e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{baseUrlMarkerPath}\" should contain \"base" +
                                                            "Url\"", null, null, "79e535ac5106d95691590c100cd00224"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{baseUrlMarkerKey}\"", null, null, "e792b542e1d19757a7251fecb05624fe"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{baseUrlMarkerPath}\"", null, null, "a62cb719cab433578d4ef284a8dd90ea")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "72559657838e1557861edab8fb3b61b6")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains endpoint paths", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"endpointMarkerPath\"", null, null, "092d85e7d2241c59b7016fd6a445eda9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{endpointMarkerPath}\" with key stored as \"endpointMa" +
                                                            "rkerKey\"", null, null, "cebd7f321f858650afd4bf88a161e79d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{endpointMarkerKey}\" is started", null, null, "6bc9757902f41152ba735d4a89493505"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{endpointMarkerPath}\" should contain \"mcp" +
                                                            "/todo\"", null, null, "b9a7b14315a3f054a7ae3508fc7f9b2c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{endpointMarkerKey}\"", null, null, "b11e866880a39b5b9818332dd7234c96"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{endpointMarkerPath}\"", null, null, "6ca28bb80afabc5d94cee65ca878d175")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0390864ea9cdcd56a2a15e2b43f6391a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Marker file contains machine-readable prompt block", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"promptMarkerPath\"", null, null, "cbde36adb338715e918ff340124cd481"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(55, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{promptMarkerPath}\" with key stored as \"promptMarker" +
                                                            "Key\"", null, null, "8001791a1b4e735eb079a1329b03f9aa"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workspace \"{promptMarkerKey}\" is started", null, null, "3ddd3cc14a14bc5585bd797a9275fa53"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{promptMarkerPath}\" should contain \"promp" +
                                                            "t\"", null, null, "0136954b0fd72f53b0ec2b28298e6c3b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I stop the workspace \"{promptMarkerKey}\"", null, null, "8792dc30c39af1538199ac077dca9ce5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{promptMarkerPath}\"", null, null, "18cc10328a19f551abcd4ffa9c7f1732")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ab55f581b180475a84a575627b788be7")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Legacy .mcp-server.yaml files are cleaned up on workspace stop", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(62, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "I use a unique temp directory stored as \"legacyMarkerPath\"", null, null, "9a831ff8ecd84a59b1f6e0c70d2f38a8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(63, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a legacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\"", null, null, "0bdcac1604eb9555b0a521be4545143a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(64, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a workspace exists for path \"{legacyMarkerPath}\" with key stored as \"legacyMarker" +
                                                            "Key\"", null, null, "e6879dd584a33f5a8a926dc5521da99d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(65, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empty body", null, null, "b3e051e14e80a55faa20172f6f26416b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(66, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "40da1118838115568a3441b06db798ec"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(67, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the file \".mcp-server.yaml\" should not exist in \"{legacyMarkerPath}\"", null, null, "47fa2cae1d9b3a5a90c5d999edc16441"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(68, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I delete the created workspace using the path \"{legacyMarkerPath}\"", null, null, "70031e6d13f6db58a13d7e033ee70e18")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3b7842808228445c94cd667c3c6228c4"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(1)), "  # FR-MCP-018 / TR-MCP-WS-005 / TEST-MCP-013")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("453cc4687e59c952b023d7ecc803fc3e", "Features/Workspace/WorkspaceMarkerFile.feature", "Workspace start writes AGENTS-README-FIRST.yaml to workspace root", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc2c402017a109588cfa217bdd4b1987"}), "e4368684111b8c5b9572df9505d1d8b6", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2f9f7a64f872ac5a98aa109e4dfd65c4"}), "e1a302cbeaca0a5aaf884323c5458ee2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"markerWsPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4a39ae1dd1c2415e8eef71e20301256d"}), "5cb5b051f291d95f85b9c89bbb8c53f3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{markerWsPath}\" with key stored as \"markerWsKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d7f0b1132b0dd850a39dfe89cb6b2197"}), "5a847cb82f0a7c55919c980630612dd1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/workspace/{markerWsKey}/start\" with empty body"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "945c90c1ef4994529a54651c90e16f55"}), "78be0ef0d9b9a05fbcac0d498762d8be", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0d2f93088e67725db5fa8b5dd31a2dea"}), "28b26fa9e880255cb5e8b7ecc64f7658", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" should exist in \"{markerWsPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f78d35e6c32b4f5ca40254d8fbce24db"}), "d277ab8e519cb1559fbe1ae0e980a4a8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{markerWsKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "047355b1ec8ad75095e716bc10839e79"}), "b9034f8c550cb959a1ca53b1932911f5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{markerWsPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6bd7a992582f8756865e3454266d06b2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("dd3040fefeab075e927c6f0988086723", "Features/Workspace/WorkspaceMarkerFile.feature", "Workspace stop removes the marker file", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc2c402017a109588cfa217bdd4b1987"}), "fcb9a9e2358a3b58bbe85c3abd2e9423", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "05a700a8edd6eb5fa361b353bf85a49a"}), "893a4551350e1758a612ea5bcc4e02c3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"stopMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0dbe9883e98cce52ac6e3c043523ba07"}), "8091f834d5cc745889a039acce1ca2e5", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{stopMarkerPath}\" with key stored as \"stopMarkerKey\"" +
                                                ""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0c797d0117ac14538db84a93c77bc965"}), "b72080e6620c1553b71e12eca8564a39", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{stopMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d8a331919980e55fa824853f6c2e67b6"}), "cf5ed73f14ecc05d89f686df05f43cf0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with empty body"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2ead7c5aea63b05c8e917a2816e7c243"}), "355423628a10f05ca1b06c2996ab0395", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b7f6e96b7d4ce352a8a223f6f7fff0b7"}), "c6e49cee3a4f6859ad3bc0f7dbf6fdf8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" should not exist in \"{stopMarkerPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c229d4540c5261509b9b3f6de2016b82"}), "95c511ddb309aa548afaf4748b4b510e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{stopMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "519e90289818175083cb77a7d6c91b0e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("baec6cc604b63c52a0bf51751c2c6b32", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains the correct port number", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc2c402017a109588cfa217bdd4b1987"}), "0ee8ee6790b3c659b2ec0454f1512276", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "07da4fd25dba1652a35dd84dfdabc6d7"}), "1d044214b957ff53be10c053e5186fce", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"portMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e68ceb8675d8dd5f8b53b40311979e2f"}), "1cc20aca9119c65aa70cc59d1cd7569b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{portMarkerPath}\" with key stored as \"portMarkerKey\"" +
                                                " and port stored as \"wsPort\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ae649483f0ccdd5dbe8fa244b16ef85a"}), "6b8d8ed980a8185eb2e1b414ccd57900", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{portMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f60be18cc9c53b58b80ea3cd6fe06e4f"}), "58e20b65c1a2d855bd66d0e30bae8ca8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{portMarkerPath}\" should contain \"{wsPort" +
                                                "}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "50bd496f5ab39357b95c4885b4a04d06"}), "89a00d09d02eb25cb34f0191334b2c40", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{portMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6b06cf8e76453b558889e82e3cd37acb"}), "d01cea03cd07c157883ec688e5818b7a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{portMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "707640aaa283bd5e91d598527724da7a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f10cf46d02b0ab5d930361b5c90469b8", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains baseUrl field", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc2c402017a109588cfa217bdd4b1987"}), "8817aeb07c79c2598c74720b9ee576b1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f1498531ee53325d8eb7598fd420bea4"}), "33ff98e2155b8b51901c18c723481877", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"baseUrlMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f3a9f62f76066d55bb9719098b0db8fa"}), "0a40baefcb63f05b9b1de656c0e892cb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{baseUrlMarkerPath}\" with key stored as \"baseUrlMark" +
                                                "erKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3e4a794a17abc3578a94925b094db27e"}), "1bf3cd9ded3200589ce593c6d54e8142", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{baseUrlMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "79e535ac5106d95691590c100cd00224"}), "43915e492db8dc568648ff3bdd5cd041", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{baseUrlMarkerPath}\" should contain \"base" +
                                                "Url\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e792b542e1d19757a7251fecb05624fe"}), "03835d7c6e2116559a3430e5b9c2ae03", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{baseUrlMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a62cb719cab433578d4ef284a8dd90ea"}), "488ed3c503c2d254aa2d3d37bdbcc550", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{baseUrlMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "72559657838e1557861edab8fb3b61b6"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e3b402d3ef9089588d0ea3dcf1c9f741", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains endpoint paths", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc2c402017a109588cfa217bdd4b1987"}), "002c725f4243175b8b7a500b615ac8cc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "092d85e7d2241c59b7016fd6a445eda9"}), "b729f1e647e5a55abcdeaa09d7d0d529", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"endpointMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cebd7f321f858650afd4bf88a161e79d"}), "91128917fccf2056849f5715858e1f2d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{endpointMarkerPath}\" with key stored as \"endpointMa" +
                                                "rkerKey\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6bc9757902f41152ba735d4a89493505"}), "a3804802d8d48d52b08b1b46f796f672", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{endpointMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b9a7b14315a3f054a7ae3508fc7f9b2c"}), "e884fdd4312de25d96acb442340af0cb", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{endpointMarkerPath}\" should contain \"mcp" +
                                                "/todo\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b11e866880a39b5b9818332dd7234c96"}), "d3f96482aee04257855f7b110cdbb4f5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{endpointMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6ca28bb80afabc5d94cee65ca878d175"}), "0475b68cd055f6579043cd69d287ed34", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{endpointMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0390864ea9cdcd56a2a15e2b43f6391a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f0a93e9acfd64f51b4e8bd2f9579bc44", "Features/Workspace/WorkspaceMarkerFile.feature", "Marker file contains machine-readable prompt block", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc2c402017a109588cfa217bdd4b1987"}), "aa4903c6c7a0a95abdfd03bf3f200767", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cbde36adb338715e918ff340124cd481"}), "7e06ce4e37ae0c56bfe264b6fd98c389", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"promptMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8001791a1b4e735eb079a1329b03f9aa"}), "7c7c2225492f695bba25fe28057048b1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{promptMarkerPath}\" with key stored as \"promptMarker" +
                                                "Key\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3ddd3cc14a14bc5585bd797a9275fa53"}), "f68874428998265994950cbd353783e1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the workspace \"{promptMarkerKey}\" is started"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0136954b0fd72f53b0ec2b28298e6c3b"}), "abcec89cc0d904599b2c58bd196eabdf", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \"AGENTS-README-FIRST.yaml\" in \"{promptMarkerPath}\" should contain \"promp" +
                                                "t\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8792dc30c39af1538199ac077dca9ce5"}), "dd70e403aa1721598ca210e418f979d2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I stop the workspace \"{promptMarkerKey}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "18cc10328a19f551abcd4ffa9c7f1732"}), "a6d0b3a635db6f5ebd61b72266a85228", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{promptMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "ab55f581b180475a84a575627b788be7"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d8ff12ac08b8c55b92ea5c61b333a415", "Features/Workspace/WorkspaceMarkerFile.feature", "Legacy .mcp-server.yaml files are cleaned up on workspace stop", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cc2c402017a109588cfa217bdd4b1987"}), "675e14fbbdce265fb8022eb6c48462de", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9a831ff8ecd84a59b1f6e0c70d2f38a8"}), "c724a11e7ee7be52bf2298683484030a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I use a unique temp directory stored as \"legacyMarkerPath\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0bdcac1604eb9555b0a521be4545143a"}), "c3b6d28c63b9465d80777e2697fd3da0", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a legacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e6879dd584a33f5a8a926dc5521da99d"}), "7f1e821c8a3bc65496e9d1ae3b59a1dd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a workspace exists for path \"{legacyMarkerPath}\" with key stored as \"legacyMarker" +
                                                "Key\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b3e051e14e80a55faa20172f6f26416b"}), "04bafad2a4568d51a7ba10fbfb961b21", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empty body"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "40da1118838115568a3441b06db798ec"}), "31b04099a3c1e75d997ef6ddc3cd4b63", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "47fa2cae1d9b3a5a90c5d999edc16441"}), "253f817df7aa87519ed0e5687236db9f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the file \".mcp-server.yaml\" should not exist in \"{legacyMarkerPath}\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70031e6d13f6db58a13d7e033ee70e18"}), "ae41ab088c96c05db284a1ac6ff2df46", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I delete the created workspace using the path \"{legacyMarkerPath}\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "3b7842808228445c94cd667c3c6228c4"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(WorkspaceMarkerFileAgentDiscoveryFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(WorkspaceMarkerFileAgentDiscoveryFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(WorkspaceMarkerFileAgentDiscoveryFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Workspace start writes AGENTS-README-FIRST.yaml to workspace root")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Workspace start writes AGENTS-README-FIRST.yaml to workspace root")]
        public async global::System.Threading.Tasks.Task WorkspaceStartWritesAGENTS_README_FIRST_YamlToWorkspaceRoot()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workspace start writes AGENTS-README-FIRST.yaml to workspace root", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.GivenAsync("I use a unique temp directory stored as \"markerWsPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
    await testRunner.AndAsync("a workspace exists for path \"{markerWsPath}\" with key stored as \"markerWsKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.WhenAsync("I POST to \"/mcp/workspace/{markerWsKey}/start\" with empty body", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
    await testRunner.AndAsync("the file \"AGENTS-README-FIRST.yaml\" should exist in \"{markerWsPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("I stop the workspace \"{markerWsKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("I delete the created workspace using the path \"{markerWsPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Workspace stop removes the marker file")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Workspace stop removes the marker file")]
        public async global::System.Threading.Tasks.Task WorkspaceStopRemovesTheMarkerFile()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Workspace stop removes the marker file", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.GivenAsync("I use a unique temp directory stored as \"stopMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.AndAsync("a workspace exists for path \"{stopMarkerPath}\" with key stored as \"stopMarkerKey\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("the workspace \"{stopMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.WhenAsync("I POST to \"/mcp/workspace/{stopMarkerKey}/stop\" with empty body", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
    await testRunner.AndAsync("the file \"AGENTS-README-FIRST.yaml\" should not exist in \"{stopMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("I delete the created workspace using the path \"{stopMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains the correct port number")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains the correct port number")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsTheCorrectPortNumber()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains the correct port number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("I use a unique temp directory stored as \"portMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.AndAsync("a workspace exists for path \"{portMarkerPath}\" with key stored as \"portMarkerKey\"" +
                        " and port stored as \"wsPort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("the workspace \"{portMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{portMarkerPath}\" should contain \"{wsPort" +
                        "}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
    await testRunner.AndAsync("I stop the workspace \"{portMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync("I delete the created workspace using the path \"{portMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains baseUrl field")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains baseUrl field")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsBaseUrlField()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains baseUrl field", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("I use a unique temp directory stored as \"baseUrlMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.AndAsync("a workspace exists for path \"{baseUrlMarkerPath}\" with key stored as \"baseUrlMark" +
                        "erKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("the workspace \"{baseUrlMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{baseUrlMarkerPath}\" should contain \"base" +
                        "Url\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.AndAsync("I stop the workspace \"{baseUrlMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.AndAsync("I delete the created workspace using the path \"{baseUrlMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains endpoint paths")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains endpoint paths")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsEndpointPaths()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains endpoint paths", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("I use a unique temp directory stored as \"endpointMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.AndAsync("a workspace exists for path \"{endpointMarkerPath}\" with key stored as \"endpointMa" +
                        "rkerKey\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.AndAsync("the workspace \"{endpointMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{endpointMarkerPath}\" should contain \"mcp" +
                        "/todo\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("I stop the workspace \"{endpointMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("I delete the created workspace using the path \"{endpointMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Marker file contains machine-readable prompt block")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Marker file contains machine-readable prompt block")]
        public async global::System.Threading.Tasks.Task MarkerFileContainsMachine_ReadablePromptBlock()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marker file contains machine-readable prompt block", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.GivenAsync("I use a unique temp directory stored as \"promptMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
    await testRunner.AndAsync("a workspace exists for path \"{promptMarkerPath}\" with key stored as \"promptMarker" +
                        "Key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.AndAsync("the workspace \"{promptMarkerKey}\" is started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.ThenAsync("the file \"AGENTS-README-FIRST.yaml\" in \"{promptMarkerPath}\" should contain \"promp" +
                        "t\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("I stop the workspace \"{promptMarkerKey}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("I delete the created workspace using the path \"{promptMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Legacy .mcp-server.yaml files are cleaned up on workspace stop")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workspace Marker File Agent Discovery")]
        [global::Xunit.TraitAttribute("Description", "Legacy .mcp-server.yaml files are cleaned up on workspace stop")]
        public async global::System.Threading.Tasks.Task Legacy_Mcp_Server_YamlFilesAreCleanedUpOnWorkspaceStop()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Legacy .mcp-server.yaml files are cleaned up on workspace stop", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
    await testRunner.GivenAsync("I use a unique temp directory stored as \"legacyMarkerPath\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
    await testRunner.AndAsync("a legacy \".mcp-server.yaml\" file exists in \"{legacyMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("a workspace exists for path \"{legacyMarkerPath}\" with key stored as \"legacyMarker" +
                        "Key\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.WhenAsync("I POST to \"/mcp/workspace/{legacyMarkerKey}/stop\" with empty body", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
    await testRunner.AndAsync("the file \".mcp-server.yaml\" should not exist in \"{legacyMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("I delete the created workspace using the path \"{legacyMarkerPath}\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WorkspaceMarkerFileAgentDiscoveryFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WorkspaceMarkerFileAgentDiscoveryFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
