using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace McpServer.Support.Mcp.Storage.PostgreSqlMigrations.Migrations
{
    /// <inheritdoc />
    public partial class AddSessionLogTagsAndAgentSessionHeaders : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "SessionLogs" ADD COLUMN IF NOT EXISTS "AgentSessionId" character varying(256);
                ALTER TABLE "SessionLogs" ADD COLUMN IF NOT EXISTS "AgentSessionTranscriptFile" character varying(2048);
                ALTER TABLE "SessionLogs" ADD COLUMN IF NOT EXISTS "AgentExecutablePath" character varying(2048);
                ALTER TABLE "SessionLogs" ADD COLUMN IF NOT EXISTS "AgentExecutableVersion" character varying(128);

                CREATE TABLE IF NOT EXISTS "SessionLogTags" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "WorkspaceId" character varying(1024) NOT NULL,
                    "SessionLogId" bigint NOT NULL,
                    "Tag" character varying(256) NOT NULL,
                    "DeleteReason" character varying(1024),
                    "DeletedAtUtc" timestamp with time zone,
                    "DeletedBy" character varying(256),
                    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                    CONSTRAINT "PK_SessionLogTags" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_SessionLogTags_SessionLogs_SessionLogId" FOREIGN KEY ("SessionLogId") REFERENCES "SessionLogs" ("Id") ON DELETE RESTRICT,
                    CONSTRAINT "FK_SessionLogTags_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId") REFERENCES "Workspaces" ("WorkspaceId") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SessionLogTags_SessionLogId_Tag" ON "SessionLogTags" ("SessionLogId", "Tag");
                CREATE INDEX IF NOT EXISTS "IX_SessionLogTags_WorkspaceId" ON "SessionLogTags" ("WorkspaceId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SessionLogTags");
        }
    }
}
