// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace McpServer.SpecFlow.Tests.Features.Context
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class HybridContextSearchFeature : object, global::Xunit.IClassFixture<HybridContextSearchFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Context", "Hybrid Context Search", "  As an AI agent\n  I want to search indexed content using hybrid FTS5 and vector " +
                "search\n  So that I can retrieve relevant context for my queries", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "HybridContextSearch.feature"
#line hidden
        
        public HybridContextSearchFeature(HybridContextSearchFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the MCP server is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Context/HybridContextSearch.feature", "Feature: Hybrid Context Search\n  As an AI agent\n  I want to search indexed conten" +
                    "t using hybrid FTS5 and vector search\n  So that I can retrieve relevant context " +
                    "for my queries\n\n  Background:\n    Given the MCP server is running\n\n  # FR-MCP-00" +
                    "4 / FR-SUPPORT-010 / TEST-MCP-004 / TR-MCP-DATA-002 / TR-MCP-DATA-003\n\n  Scenari" +
                    "o: Context search returns 200 with results\n    When I POST to \"/mcp/context/sear" +
                    "ch\" with body:\n      \"\"\"\n      { \"query\": \"test\", \"limit\": 5 }\n      \"\"\"\n    The" +
                    "n the response status code should be 200\n    And the response body should contai" +
                    "n \"chunks\"\n\n  Scenario: Context search with source type filter restricts results" +
                    "\n    When I POST to \"/mcp/context/search\" with body:\n      \"\"\"\n      { \"query\": " +
                    "\"test\", \"sourceType\": \"todo\", \"limit\": 10 }\n      \"\"\"\n    Then the response stat" +
                    "us code should be 200\n\n  Scenario: Context search clamps limit to maximum of 100" +
                    "\n    When I POST to \"/mcp/context/search\" with body:\n      \"\"\"\n      { \"query\": " +
                    "\"test\", \"limit\": 9999 }\n      \"\"\"\n    Then the response status code should be 20" +
                    "0\n\n  Scenario: Context search clamps limit to minimum of 1\n    When I POST to \"/" +
                    "mcp/context/search\" with body:\n      \"\"\"\n      { \"query\": \"test\", \"limit\": 0 }\n " +
                    "     \"\"\"\n    Then the response status code should be 200\n\n  Scenario: Context pa" +
                    "ck returns ordered chunks with sourceKeys\n    When I POST to \"/mcp/context/pack\"" +
                    " with body:\n      \"\"\"\n      { \"queryId\": \"specflow-test-query\", \"query\": \"test c" +
                    "ontext\", \"limit\": 3 }\n      \"\"\"\n    Then the response status code should be 200\n" +
                    "    And the response body should contain \"queryId\"\n\n  Scenario: Context sources " +
                    "returns indexed document list\n    When I send a GET request to \"/mcp/context/sou" +
                    "rces\"\n    Then the response status code should be 200\n\n  Scenario: Context searc" +
                    "h empty query still returns 200\n    When I POST to \"/mcp/context/search\" with bo" +
                    "dy:\n      \"\"\"\n      { \"query\": \"\", \"limit\": 5 }\n      \"\"\"\n    Then the response " +
                    "status code should be 200\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Context/HybridContextSearch.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Hybrid Context Search", "  As an AI agent\n  I want to search indexed content using hybrid FTS5 and vector " +
                        "search\n  So that I can retrieve relevant context for my queries", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the MCP server is running", null, null, "28dce92025ca2d53bc6b826237cd2582")}), "79e227368d64e75f87e7cc5de83b4d63"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search returns 200 with results", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"limit\": 5 }", "\"\"\""), null, "acee38fa5774e75eb5912db7055584c6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "00f827c4ba60215f9b6a941b167190eb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response body should contain \"chunks\"", null, null, "363db17e11ff7c598328fb8e07e9cfbd")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "50fc65e3969ef359b7cfef4993e65385")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search with source type filter restricts results", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"sourceType\": \"todo\", \"limit\": 10 }", "\"\"\""), null, "6b6bfa356920ab50b2ce882d21b8390a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "8664041834bc82549f3bdaab7512095d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a39295dfabc46f59b9ab3b5497adfd1c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search clamps limit to maximum of 100", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"limit\": 9999 }", "\"\"\""), null, "140de51dad8a7257b5226dd98dca6989"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "3f39a7fa9c4df55194df6b31db897a73")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e26ff673a38cad52a9beb9c393e6ae91")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search clamps limit to minimum of 1", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"limit\": 0 }", "\"\"\""), null, "24a0d32169d401528da007bff1025630"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "f7c6552c1b7ef45f8ad560faffbeb977")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3f57703dd1d24455800241cd143b6db0")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context pack returns ordered chunks with sourceKeys", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/pack\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(7)), null, "{ \"queryId\": \"specflow-test-query\", \"query\": \"test context\", \"limit\": 3 }", "\"\"\""), null, "c81270faf8811d538fc1d5cbd1b2325d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "daa30ac5df9b9b5391cabfed4ff0b645"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response body should contain \"queryId\"", null, null, "9ade2dfac7f0b759a74e69fd99690a3c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6d92b24ec611ee5db03e2c4a614520d8")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context sources returns indexed document list", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/context/sources\"", null, null, "626ba320f6167e5596c9460d5d56f248"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "122004a2b35a6c5c9a90bc2568e222c8")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d680d8f607d7cd54b65b00ee9ffc548c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search empty query still returns 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(7)), null, "{ \"query\": \"\", \"limit\": 5 }", "\"\"\""), null, "a1ac7ee8ce7e8e51bce8b921b710be10"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "1d869f1368a86f548688712568889fa1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "6f86b1ac12f4a758b24730cce8ef2405"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(1)), "  # FR-MCP-004 / FR-SUPPORT-010 / TEST-MCP-004 / TR-MCP-DATA-002 / TR-MCP-DATA-00" +
                                    "3")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("de9b2a37eafdeb5bbb4c4bb7d623ee41", "Features/Context/HybridContextSearch.feature", "Context search returns 200 with results", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28dce92025ca2d53bc6b826237cd2582"}), "4d66155a35ade050b97834e01aac4640", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"limit\": 5 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "acee38fa5774e75eb5912db7055584c6"}), "e5070831485ef05dadcb16a36bab6b6b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "00f827c4ba60215f9b6a941b167190eb"}), "cebb344a2d6cd75b92a03090b86633bb", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "363db17e11ff7c598328fb8e07e9cfbd"}), "f09b4459fcd6ee5ba0f0b08bfa81abf2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response body should contain \"chunks\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "50fc65e3969ef359b7cfef4993e65385"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("8b8d5ed00ebfb757bd8cb829ff610af1", "Features/Context/HybridContextSearch.feature", "Context search with source type filter restricts results", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28dce92025ca2d53bc6b826237cd2582"}), "ef14ef779e8b3657a9f592237eb6cf84", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"sourceType\": \"todo\", \"limit\": 10 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "6b6bfa356920ab50b2ce882d21b8390a"}), "6f0639501c343952a73a450ed5171a26", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8664041834bc82549f3bdaab7512095d"}), "5bf9f947a813c356849829fd6960b6ef", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "a39295dfabc46f59b9ab3b5497adfd1c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b2be098657cac857854a5d7136821b4d", "Features/Context/HybridContextSearch.feature", "Context search clamps limit to maximum of 100", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28dce92025ca2d53bc6b826237cd2582"}), "4cab4a78611638578ff2c6775a413283", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"limit\": 9999 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "140de51dad8a7257b5226dd98dca6989"}), "3fca8ba00917ba5a8f2eb23dc5e3939e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3f39a7fa9c4df55194df6b31db897a73"}), "8f47e5a31be383519a4e5f437a9456f7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e26ff673a38cad52a9beb9c393e6ae91"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d1cf816686ef6c538875e38ec88edcf8", "Features/Context/HybridContextSearch.feature", "Context search clamps limit to minimum of 1", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28dce92025ca2d53bc6b826237cd2582"}), "3469b5e98c6ffe5ba20cb269f5dff109", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"limit\": 0 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "24a0d32169d401528da007bff1025630"}), "4810946a798490569831d572f662c887", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f7c6552c1b7ef45f8ad560faffbeb977"}), "3fb67448bc32515bb4c3cebf2fe00b57", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "3f57703dd1d24455800241cd143b6db0"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("978bc4f9e5a1d75393ddd2629c257aa9", "Features/Context/HybridContextSearch.feature", "Context pack returns ordered chunks with sourceKeys", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28dce92025ca2d53bc6b826237cd2582"}), "90f48f6997c7675daf28babdbffbac86", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"queryId\": \"specflow-test-query\", \"query\": \"test context\", \"limit\": 3 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "c81270faf8811d538fc1d5cbd1b2325d"}), "c9d800172969595b83af7db3d91de6e6", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/pack\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "daa30ac5df9b9b5391cabfed4ff0b645"}), "6bc13b79ca4da55c89c2b38d410bab30", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9ade2dfac7f0b759a74e69fd99690a3c"}), "44b7974893849c50a930949e8a6ca2ac", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response body should contain \"queryId\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6d92b24ec611ee5db03e2c4a614520d8"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("2be3c3b1e0741459bee60a6728981e7c", "Features/Context/HybridContextSearch.feature", "Context sources returns indexed document list", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28dce92025ca2d53bc6b826237cd2582"}), "abca0bd6e6ddcd5f95a3f40189f2cc8b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "626ba320f6167e5596c9460d5d56f248"}), "a8332a994cc38e52a034b92fb1cded15", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/context/sources\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "122004a2b35a6c5c9a90bc2568e222c8"}), "797370f5fef8655ea769656d065f2be0", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "d680d8f607d7cd54b65b00ee9ffc548c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3b6d19f4211ab05aa88c6a4e17b1b924", "Features/Context/HybridContextSearch.feature", "Context search empty query still returns 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "28dce92025ca2d53bc6b826237cd2582"}), "62fa610331890d55bbebeeeeedc06ce7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"\", \"limit\": 5 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "a1ac7ee8ce7e8e51bce8b921b710be10"}), "1d84ab3174d8865b8505dd66475a50de", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1d869f1368a86f548688712568889fa1"}), "5b4aa990cfd5635da3e8c9f14c782a04", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "6f86b1ac12f4a758b24730cce8ef2405"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(HybridContextSearchFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(HybridContextSearchFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(HybridContextSearchFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search returns 200 with results")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search returns 200 with results")]
        public async global::System.Threading.Tasks.Task ContextSearchReturns200WithResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search returns 200 with results", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"limit\": 5 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.AndAsync("the response body should contain \"chunks\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search with source type filter restricts results")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search with source type filter restricts results")]
        public async global::System.Threading.Tasks.Task ContextSearchWithSourceTypeFilterRestrictsResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search with source type filter restricts results", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"sourceType\": \"todo\", \"limit\": 10 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search clamps limit to maximum of 100")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search clamps limit to maximum of 100")]
        public async global::System.Threading.Tasks.Task ContextSearchClampsLimitToMaximumOf100()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search clamps limit to maximum of 100", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"limit\": 9999 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search clamps limit to minimum of 1")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search clamps limit to minimum of 1")]
        public async global::System.Threading.Tasks.Task ContextSearchClampsLimitToMinimumOf1()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search clamps limit to minimum of 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 34
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"limit\": 0 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context pack returns ordered chunks with sourceKeys")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context pack returns ordered chunks with sourceKeys")]
        public async global::System.Threading.Tasks.Task ContextPackReturnsOrderedChunksWithSourceKeys()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context pack returns ordered chunks with sourceKeys", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.WhenAsync("I POST to \"/mcp/context/pack\" with body:", "{ \"queryId\": \"specflow-test-query\", \"query\": \"test context\", \"limit\": 3 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
    await testRunner.AndAsync("the response body should contain \"queryId\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context sources returns indexed document list")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context sources returns indexed document list")]
        public async global::System.Threading.Tasks.Task ContextSourcesReturnsIndexedDocumentList()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context sources returns indexed document list", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.WhenAsync("I send a GET request to \"/mcp/context/sources\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search empty query still returns 200")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search empty query still returns 200")]
        public async global::System.Threading.Tasks.Task ContextSearchEmptyQueryStillReturns200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search empty query still returns 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 53
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"\", \"limit\": 5 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await HybridContextSearchFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await HybridContextSearchFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
