// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace McpServer.SpecFlow.Tests.Features.Context
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class HybridContextSearchFeature : object, global::Xunit.IClassFixture<HybridContextSearchFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Context", "Hybrid Context Search", "  As an AI agent\r\n  I want to search indexed content using hybrid FTS5 and vector" +
                " search\r\n  So that I can retrieve relevant context for my queries", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "HybridContextSearch.feature"
#line hidden
        
        public HybridContextSearchFeature(HybridContextSearchFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the MCP server is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Context/HybridContextSearch.feature", "Feature: Hybrid Context Search\r\n  As an AI agent\r\n  I want to search indexed cont" +
                    "ent using hybrid FTS5 and vector search\r\n  So that I can retrieve relevant conte" +
                    "xt for my queries\r\n\r\n  Background:\r\n    Given the MCP server is running\r\n\r\n  # F" +
                    "R-MCP-004 / FR-SUPPORT-010 / TEST-MCP-004 / TR-MCP-DATA-002 / TR-MCP-DATA-003\r\n\r" +
                    "\n  Scenario: Context search returns 200 with results\r\n    When I POST to \"/mcp/c" +
                    "ontext/search\" with body:\r\n      \"\"\"\r\n      { \"query\": \"test\", \"limit\": 5 }\r\n   " +
                    "   \"\"\"\r\n    Then the response status code should be 200\r\n    And the response bo" +
                    "dy should contain \"chunks\"\r\n\r\n  Scenario: Context search with source type filter" +
                    " restricts results\r\n    When I POST to \"/mcp/context/search\" with body:\r\n      \"" +
                    "\"\"\r\n      { \"query\": \"test\", \"sourceType\": \"todo\", \"limit\": 10 }\r\n      \"\"\"\r\n   " +
                    " Then the response status code should be 200\r\n\r\n  Scenario: Context search clamp" +
                    "s limit to maximum of 100\r\n    When I POST to \"/mcp/context/search\" with body:\r\n" +
                    "      \"\"\"\r\n      { \"query\": \"test\", \"limit\": 9999 }\r\n      \"\"\"\r\n    Then the res" +
                    "ponse status code should be 200\r\n\r\n  Scenario: Context search clamps limit to mi" +
                    "nimum of 1\r\n    When I POST to \"/mcp/context/search\" with body:\r\n      \"\"\"\r\n    " +
                    "  { \"query\": \"test\", \"limit\": 0 }\r\n      \"\"\"\r\n    Then the response status code " +
                    "should be 200\r\n\r\n  Scenario: Context pack returns ordered chunks with sourceKeys" +
                    "\r\n    When I POST to \"/mcp/context/pack\" with body:\r\n      \"\"\"\r\n      { \"queryId" +
                    "\": \"specflow-test-query\", \"query\": \"test context\", \"limit\": 3 }\r\n      \"\"\"\r\n    " +
                    "Then the response status code should be 200\r\n    And the response body should co" +
                    "ntain \"queryId\"\r\n\r\n  Scenario: Context sources returns indexed document list\r\n  " +
                    "  When I send a GET request to \"/mcp/context/sources\"\r\n    Then the response sta" +
                    "tus code should be 200\r\n\r\n  Scenario: Context search empty query still returns 2" +
                    "00\r\n    When I POST to \"/mcp/context/search\" with body:\r\n      \"\"\"\r\n      { \"que" +
                    "ry\": \"\", \"limit\": 5 }\r\n      \"\"\"\r\n    Then the response status code should be 20" +
                    "0\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Context/HybridContextSearch.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Hybrid Context Search", "  As an AI agent\r\n  I want to search indexed content using hybrid FTS5 and vector" +
                        " search\r\n  So that I can retrieve relevant context for my queries", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the MCP server is running", null, null, "753a9b8a87be3450ae6f9a1ea3bec3d8")}), "27fd157a4dcf8a5f87f8592ef7bf87fc"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search returns 200 with results", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"limit\": 5 }", "\"\"\""), null, "4e569e2855d5fa5b97495dfa56d2e9b8"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "0bd08bfe2450a251afdd66cafff9522a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response body should contain \"chunks\"", null, null, "d8b6146ab991fe59bee49b72aca327fb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b6922ea0e3da70509c573ee2ded57616")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search with source type filter restricts results", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"sourceType\": \"todo\", \"limit\": 10 }", "\"\"\""), null, "528c8ea6f0afdd54b40edaed2ae078bd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "d0ce2e4cb828865b8f9279a666897483")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "834fe85e8a2f5651b638ad60aba25846")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search clamps limit to maximum of 100", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"limit\": 9999 }", "\"\"\""), null, "8b8878a073ccd253a52c265cdefedc04"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "bb4050183a967f5ebbe9e026abcded73")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "006780df077c0c54aa6e550bab63d9ef")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search clamps limit to minimum of 1", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(7)), null, "{ \"query\": \"test\", \"limit\": 0 }", "\"\"\""), null, "207ec02109a70154a6c85a543cf13c73"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "e3b45c2aa2a0865591960e6c498114db")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e18bbed7d404f758b24a3dc87514e166")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(40, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context pack returns ordered chunks with sourceKeys", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/pack\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(7)), null, "{ \"queryId\": \"specflow-test-query\", \"query\": \"test context\", \"limit\": 3 }", "\"\"\""), null, "c44b133228c3135b8776fd588b563b01"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "c4581dbf8e7c8e529652c99b1677f138"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the response body should contain \"queryId\"", null, null, "41e636146640c653b93ddef2609e15c5")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "709c97256b7bd85f84a2ec0ad64ced6c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(48, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context sources returns indexed document list", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I send a GET request to \"/mcp/context/sources\"", null, null, "fc959a6aaf7db65da90b1913bf0bc024"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "8d2c5310cb85a053a5d1d73b6031e5f0")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "cc2f6e916bd0f9568d8353a680645fb2")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Context search empty query still returns 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I POST to \"/mcp/context/search\" with body:", new global::Io.Cucumber.Messages.Types.DocString(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(7)), null, "{ \"query\": \"\", \"limit\": 5 }", "\"\"\""), null, "19d48b326361485f9930a42244d25377"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the response status code should be 200", null, null, "2088636de0c8db55bb812f0b58ac5e95")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "bc1002e380e2b15894650619583f22c1"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[] {
                            new global::Io.Cucumber.Messages.Types.Comment(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(1)), "  # FR-MCP-004 / FR-SUPPORT-010 / TEST-MCP-004 / TR-MCP-DATA-002 / TR-MCP-DATA-00" +
                                    "3")}));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("05de9376c61b9d5382f9b78aaa402154", "Features/Context/HybridContextSearch.feature", "Context search returns 200 with results", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "753a9b8a87be3450ae6f9a1ea3bec3d8"}), "505a51437238b75295e4c71f9076c9fb", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"limit\": 5 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "4e569e2855d5fa5b97495dfa56d2e9b8"}), "c7f395b7fee2fa5d9dc2ebbe3dbb20c0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0bd08bfe2450a251afdd66cafff9522a"}), "10d1e3cca2697654a9437a9978c2220f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d8b6146ab991fe59bee49b72aca327fb"}), "f52d02a34dbeaf5d91dd0ca0d5e05dde", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response body should contain \"chunks\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "b6922ea0e3da70509c573ee2ded57616"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6aeef2d4730efd55b0031adf8ab5ca33", "Features/Context/HybridContextSearch.feature", "Context search with source type filter restricts results", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "753a9b8a87be3450ae6f9a1ea3bec3d8"}), "e7394286fa207d58b07cf843b480071e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"sourceType\": \"todo\", \"limit\": 10 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "528c8ea6f0afdd54b40edaed2ae078bd"}), "fc1e43be0c3566599ce6c05b7b44cda9", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d0ce2e4cb828865b8f9279a666897483"}), "dda7f8088c330856baeefce3b7a83f4e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "834fe85e8a2f5651b638ad60aba25846"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("2882d5ab384a2d5ab3ef2b11ca4274a9", "Features/Context/HybridContextSearch.feature", "Context search clamps limit to maximum of 100", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "753a9b8a87be3450ae6f9a1ea3bec3d8"}), "298495189ebeb756898e0e7fb4c52fbd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"limit\": 9999 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "8b8878a073ccd253a52c265cdefedc04"}), "8633786db271425a9de90302a8c01716", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bb4050183a967f5ebbe9e026abcded73"}), "008ae349f617e458b0390a2ae62b7368", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "006780df077c0c54aa6e550bab63d9ef"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f49fd45619a2db55ae39f9018011a9a2", "Features/Context/HybridContextSearch.feature", "Context search clamps limit to minimum of 1", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "753a9b8a87be3450ae6f9a1ea3bec3d8"}), "94909a59fd4faf5b8bc17d847b16e311", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"test\", \"limit\": 0 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "207ec02109a70154a6c85a543cf13c73"}), "42cb3d5a8502da5a8af5145e12c9d355", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e3b45c2aa2a0865591960e6c498114db"}), "509620c2742d3d57abb26fc5f9a367c3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e18bbed7d404f758b24a3dc87514e166"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("08e1c7e8ee9528579c62bfcffed272e5", "Features/Context/HybridContextSearch.feature", "Context pack returns ordered chunks with sourceKeys", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "753a9b8a87be3450ae6f9a1ea3bec3d8"}), "eea65febe5b9d650bfc5bc2d470bd111", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"queryId\": \"specflow-test-query\", \"query\": \"test context\", \"limit\": 3 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "c44b133228c3135b8776fd588b563b01"}), "40888f34cc63605cb243d48cbfb9b49b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/pack\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c4581dbf8e7c8e529652c99b1677f138"}), "e1711e0c5461dc55a28441ecce30ac2f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "41e636146640c653b93ddef2609e15c5"}), "61e3586e7b61fa57888583688f5e37c6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response body should contain \"queryId\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "709c97256b7bd85f84a2ec0ad64ced6c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("7fbcedd1339af050b01e928fe80819f5", "Features/Context/HybridContextSearch.feature", "Context sources returns indexed document list", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "753a9b8a87be3450ae6f9a1ea3bec3d8"}), "e2ffc17c190c6c518d9485db8bfec85d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fc959a6aaf7db65da90b1913bf0bc024"}), "ac16b74893b7a058969e01c10118a40c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I send a GET request to \"/mcp/context/sources\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8d2c5310cb85a053a5d1d73b6031e5f0"}), "a0878eae3fc05756b459f7293bc093a6", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "cc2f6e916bd0f9568d8353a680645fb2"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("fd84f230acdc8b5db81ca2a2800f4279", "Features/Context/HybridContextSearch.feature", "Context search empty query still returns 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "753a9b8a87be3450ae6f9a1ea3bec3d8"}), "7c7dcf50bcadca59b01da6885cb569d4", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the MCP server is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(new global::Io.Cucumber.Messages.Types.PickleStepArgument(new global::Io.Cucumber.Messages.Types.PickleDocString(null, "{ \"query\": \"\", \"limit\": 5 }"), null), new System.Collections.Generic.List<string>(new string[] {
                                                        "19d48b326361485f9930a42244d25377"}), "86b6b1422f19355792eab4be113052d1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I POST to \"/mcp/context/search\" with body:"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2088636de0c8db55bb812f0b58ac5e95"}), "372818f7e305db5d9ebbf9b11fdc2711", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the response status code should be 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "bc1002e380e2b15894650619583f22c1"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(HybridContextSearchFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(HybridContextSearchFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(HybridContextSearchFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search returns 200 with results")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search returns 200 with results")]
        public async global::System.Threading.Tasks.Task ContextSearchReturns200WithResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search returns 200 with results", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"limit\": 5 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
    await testRunner.AndAsync("the response body should contain \"chunks\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search with source type filter restricts results")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search with source type filter restricts results")]
        public async global::System.Threading.Tasks.Task ContextSearchWithSourceTypeFilterRestrictsResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search with source type filter restricts results", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"sourceType\": \"todo\", \"limit\": 10 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search clamps limit to maximum of 100")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search clamps limit to maximum of 100")]
        public async global::System.Threading.Tasks.Task ContextSearchClampsLimitToMaximumOf100()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search clamps limit to maximum of 100", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"limit\": 9999 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search clamps limit to minimum of 1")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search clamps limit to minimum of 1")]
        public async global::System.Threading.Tasks.Task ContextSearchClampsLimitToMinimumOf1()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search clamps limit to minimum of 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 34
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"test\", \"limit\": 0 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context pack returns ordered chunks with sourceKeys")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context pack returns ordered chunks with sourceKeys")]
        public async global::System.Threading.Tasks.Task ContextPackReturnsOrderedChunksWithSourceKeys()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context pack returns ordered chunks with sourceKeys", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.WhenAsync("I POST to \"/mcp/context/pack\" with body:", "{ \"queryId\": \"specflow-test-query\", \"query\": \"test context\", \"limit\": 3 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 46
    await testRunner.AndAsync("the response body should contain \"queryId\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context sources returns indexed document list")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context sources returns indexed document list")]
        public async global::System.Threading.Tasks.Task ContextSourcesReturnsIndexedDocumentList()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context sources returns indexed document list", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.WhenAsync("I send a GET request to \"/mcp/context/sources\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Context search empty query still returns 200")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Hybrid Context Search")]
        [global::Xunit.TraitAttribute("Description", "Context search empty query still returns 200")]
        public async global::System.Threading.Tasks.Task ContextSearchEmptyQueryStillReturns200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Context search empty query still returns 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 53
    await testRunner.WhenAsync("I POST to \"/mcp/context/search\" with body:", "{ \"query\": \"\", \"limit\": 5 }", ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("the response status code should be 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await HybridContextSearchFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await HybridContextSearchFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
